word(a, [a]).
word(abandon, [a,b,a,n,d,o,n]).
word(ability, [a,b,i,l,i,t,y]).
word(able, [a,b,l,e]).
word(abortion, [a,b,o,r,t,i,o,n]).
word(about, [a,b,o,u,t]).
word(above, [a,b,o,v,e]).
word(abroad, [a,b,r,o,a,d]).
word(absence, [a,b,s,e,n,c,e]).
word(absolute, [a,b,s,o,l,u,t,e]).
word(absolutely, [a,b,s,o,l,u,t,e,l,y]).
word(absorb, [a,b,s,o,r,b]).
word(abuse, [a,b,u,s,e]).
word(academic, [a,c,a,d,e,m,i,c]).
word(accept, [a,c,c,e,p,t]).
word(access, [a,c,c,e,s,s]).
word(accident, [a,c,c,i,d,e,n,t]).
word(accompany, [a,c,c,o,m,p,a,n,y]).
word(accomplish, [a,c,c,o,m,p,l,i,s,h]).
word(according, [a,c,c,o,r,d,i,n,g]).
word(account, [a,c,c,o,u,n,t]).
word(accurate, [a,c,c,u,r,a,t,e]).
word(accuse, [a,c,c,u,s,e]).
word(achieve, [a,c,h,i,e,v,e]).
word(achievement, [a,c,h,i,e,v,e,m,e,n,t]).
word(acid, [a,c,i,d]).
word(acknowledge, [a,c,k,n,o,w,l,e,d,g,e]).
word(acquire, [a,c,q,u,i,r,e]).
word(across, [a,c,r,o,s,s]).
word(act, [a,c,t]).
word(action, [a,c,t,i,o,n]).
word(active, [a,c,t,i,v,e]).
word(activist, [a,c,t,i,v,i,s,t]).
word(activity, [a,c,t,i,v,i,t,y]).
word(actor, [a,c,t,o,r]).
word(actress, [a,c,t,r,e,s,s]).
word(actual, [a,c,t,u,a,l]).
word(actually, [a,c,t,u,a,l,l,y]).
word(ad, [a,d]).
word(adapt, [a,d,a,p,t]).
word(add, [a,d,d]).
word(addition, [a,d,d,i,t,i,o,n]).
word(additional, [a,d,d,i,t,i,o,n,a,l]).
word(address, [a,d,d,r,e,s,s]).
word(adequate, [a,d,e,q,u,a,t,e]).
word(adjust, [a,d,j,u,s,t]).
word(adjustment, [a,d,j,u,s,t,m,e,n,t]).
word(administration, [a,d,m,i,n,i,s,t,r,a,t,i,o,n]).
word(administrator, [a,d,m,i,n,i,s,t,r,a,t,o,r]).
word(admire, [a,d,m,i,r,e]).
word(admission, [a,d,m,i,s,s,i,o,n]).
word(admit, [a,d,m,i,t]).
word(adolescent, [a,d,o,l,e,s,c,e,n,t]).
word(adopt, [a,d,o,p,t]).
word(adult, [a,d,u,l,t]).
word(advance, [a,d,v,a,n,c,e]).
word(advanced, [a,d,v,a,n,c,e,d]).
word(advantage, [a,d,v,a,n,t,a,g,e]).
word(adventure, [a,d,v,e,n,t,u,r,e]).
word(advertising, [a,d,v,e,r,t,i,s,i,n,g]).
word(advice, [a,d,v,i,c,e]).
word(advise, [a,d,v,i,s,e]).
word(adviser, [a,d,v,i,s,e,r]).
word(advocate, [a,d,v,o,c,a,t,e]).
word(affair, [a,f,f,a,i,r]).
word(affect, [a,f,f,e,c,t]).
word(afford, [a,f,f,o,r,d]).
word(afraid, [a,f,r,a,i,d]).
word(african, [a,f,r,i,c,a,n]).
word(after, [a,f,t,e,r]).
word(afternoon, [a,f,t,e,r,n,o,o,n]).
word(again, [a,g,a,i,n]).
word(against, [a,g,a,i,n,s,t]).
word(age, [a,g,e]).
word(agency, [a,g,e,n,c,y]).
word(agenda, [a,g,e,n,d,a]).
word(agent, [a,g,e,n,t]).
word(aggressive, [a,g,g,r,e,s,s,i,v,e]).
word(ago, [a,g,o]).
word(agree, [a,g,r,e,e]).
word(agreement, [a,g,r,e,e,m,e,n,t]).
word(agricultural, [a,g,r,i,c,u,l,t,u,r,a,l]).
word(ah, [a,h]).
word(ahead, [a,h,e,a,d]).
word(aid, [a,i,d]).
word(aide, [a,i,d,e]).
word(aids, [a,i,d,s]).
word(aim, [a,i,m]).
word(air, [a,i,r]).
word(aircraft, [a,i,r,c,r,a,f,t]).
word(airline, [a,i,r,l,i,n,e]).
word(airport, [a,i,r,p,o,r,t]).
word(album, [a,l,b,u,m]).
word(alcohol, [a,l,c,o,h,o,l]).
word(alive, [a,l,i,v,e]).
word(all, [a,l,l]).
word(alliance, [a,l,l,i,a,n,c,e]).
word(allow, [a,l,l,o,w]).
word(ally, [a,l,l,y]).
word(almost, [a,l,m,o,s,t]).
word(alone, [a,l,o,n,e]).
word(along, [a,l,o,n,g]).
word(already, [a,l,r,e,a,d,y]).
word(also, [a,l,s,o]).
word(alter, [a,l,t,e,r]).
word(alternative, [a,l,t,e,r,n,a,t,i,v,e]).
word(although, [a,l,t,h,o,u,g,h]).
word(always, [a,l,w,a,y,s]).
word(am, [a,m]).
word(amazing, [a,m,a,z,i,n,g]).
word(american, [a,m,e,r,i,c,a,n]).
word(among, [a,m,o,n,g]).
word(amount, [a,m,o,u,n,t]).
word(analysis, [a,n,a,l,y,s,i,s]).
word(analyst, [a,n,a,l,y,s,t]).
word(analyze, [a,n,a,l,y,z,e]).
word(ancient, [a,n,c,i,e,n,t]).
word(and, [a,n,d]).
word(anger, [a,n,g,e,r]).
word(angle, [a,n,g,l,e]).
word(angry, [a,n,g,r,y]).
word(animal, [a,n,i,m,a,l]).
word(anniversary, [a,n,n,i,v,e,r,s,a,r,y]).
word(announce, [a,n,n,o,u,n,c,e]).
word(annual, [a,n,n,u,a,l]).
word(another, [a,n,o,t,h,e,r]).
word(answer, [a,n,s,w,e,r]).
word(anticipate, [a,n,t,i,c,i,p,a,t,e]).
word(anxiety, [a,n,x,i,e,t,y]).
word(any, [a,n,y]).
word(anybody, [a,n,y,b,o,d,y]).
word(anymore, [a,n,y,m,o,r,e]).
word(anyone, [a,n,y,o,n,e]).
word(anything, [a,n,y,t,h,i,n,g]).
word(anyway, [a,n,y,w,a,y]).
word(anywhere, [a,n,y,w,h,e,r,e]).
word(apart, [a,p,a,r,t]).
word(apartment, [a,p,a,r,t,m,e,n,t]).
word(apparent, [a,p,p,a,r,e,n,t]).
word(apparently, [a,p,p,a,r,e,n,t,l,y]).
word(appeal, [a,p,p,e,a,l]).
word(appear, [a,p,p,e,a,r]).
word(appearance, [a,p,p,e,a,r,a,n,c,e]).
word(apple, [a,p,p,l,e]).
word(application, [a,p,p,l,i,c,a,t,i,o,n]).
word(apply, [a,p,p,l,y]).
word(appoint, [a,p,p,o,i,n,t]).
word(appointment, [a,p,p,o,i,n,t,m,e,n,t]).
word(appreciate, [a,p,p,r,e,c,i,a,t,e]).
word(approach, [a,p,p,r,o,a,c,h]).
word(appropriate, [a,p,p,r,o,p,r,i,a,t,e]).
word(approval, [a,p,p,r,o,v,a,l]).
word(approve, [a,p,p,r,o,v,e]).
word(approximately, [a,p,p,r,o,x,i,m,a,t,e,l,y]).
word(arab, [a,r,a,b]).
word(architect, [a,r,c,h,i,t,e,c,t]).
word(area, [a,r,e,a]).
word(argue, [a,r,g,u,e]).
word(argument, [a,r,g,u,m,e,n,t]).
word(arise, [a,r,i,s,e]).
word(arm, [a,r,m]).
word(armed, [a,r,m,e,d]).
word(army, [a,r,m,y]).
word(around, [a,r,o,u,n,d]).
word(arrange, [a,r,r,a,n,g,e]).
word(arrangement, [a,r,r,a,n,g,e,m,e,n,t]).
word(arrest, [a,r,r,e,s,t]).
word(arrival, [a,r,r,i,v,a,l]).
word(arrive, [a,r,r,i,v,e]).
word(art, [a,r,t]).
word(article, [a,r,t,i,c,l,e]).
word(artist, [a,r,t,i,s,t]).
word(artistic, [a,r,t,i,s,t,i,c]).
word(as, [a,s]).
word(asian, [a,s,i,a,n]).
word(aside, [a,s,i,d,e]).
word(ask, [a,s,k]).
word(asleep, [a,s,l,e,e,p]).
word(aspect, [a,s,p,e,c,t]).
word(assault, [a,s,s,a,u,l,t]).
word(assert, [a,s,s,e,r,t]).
word(assess, [a,s,s,e,s,s]).
word(assessment, [a,s,s,e,s,s,m,e,n,t]).
word(asset, [a,s,s,e,t]).
word(assign, [a,s,s,i,g,n]).
word(assignment, [a,s,s,i,g,n,m,e,n,t]).
word(assist, [a,s,s,i,s,t]).
word(assistance, [a,s,s,i,s,t,a,n,c,e]).
word(assistant, [a,s,s,i,s,t,a,n,t]).
word(associate, [a,s,s,o,c,i,a,t,e]).
word(association, [a,s,s,o,c,i,a,t,i,o,n]).
word(assume, [a,s,s,u,m,e]).
word(assumption, [a,s,s,u,m,p,t,i,o,n]).
word(assure, [a,s,s,u,r,e]).
word(at, [a,t]).
word(athlete, [a,t,h,l,e,t,e]).
word(athletic, [a,t,h,l,e,t,i,c]).
word(atmosphere, [a,t,m,o,s,p,h,e,r,e]).
word(attach, [a,t,t,a,c,h]).
word(attack, [a,t,t,a,c,k]).
word(attempt, [a,t,t,e,m,p,t]).
word(attend, [a,t,t,e,n,d]).
word(attention, [a,t,t,e,n,t,i,o,n]).
word(attitude, [a,t,t,i,t,u,d,e]).
word(attorney, [a,t,t,o,r,n,e,y]).
word(attract, [a,t,t,r,a,c,t]).
word(attractive, [a,t,t,r,a,c,t,i,v,e]).
word(attribute, [a,t,t,r,i,b,u,t,e]).
word(audience, [a,u,d,i,e,n,c,e]).
word(author, [a,u,t,h,o,r]).
word(authority, [a,u,t,h,o,r,i,t,y]).
word(auto, [a,u,t,o]).
word(available, [a,v,a,i,l,a,b,l,e]).
word(average, [a,v,e,r,a,g,e]).
word(avoid, [a,v,o,i,d]).
word(award, [a,w,a,r,d]).
word(aware, [a,w,a,r,e]).
word(awareness, [a,w,a,r,e,n,e,s,s]).
word(away, [a,w,a,y]).
word(awful, [a,w,f,u,l]).
word(baby, [b,a,b,y]).
word(back, [b,a,c,k]).
word(background, [b,a,c,k,g,r,o,u,n,d]).
word(bad, [b,a,d]).
word(badly, [b,a,d,l,y]).
word(bag, [b,a,g]).
word(bake, [b,a,k,e]).
word(balance, [b,a,l,a,n,c,e]).
word(ball, [b,a,l,l]).
word(ban, [b,a,n]).
word(band, [b,a,n,d]).
word(bank, [b,a,n,k]).
word(bar, [b,a,r]).
word(barely, [b,a,r,e,l,y]).
word(barrel, [b,a,r,r,e,l]).
word(barrier, [b,a,r,r,i,e,r]).
word(base, [b,a,s,e]).
word(baseball, [b,a,s,e,b,a,l,l]).
word(basic, [b,a,s,i,c]).
word(basically, [b,a,s,i,c,a,l,l,y]).
word(basis, [b,a,s,i,s]).
word(basket, [b,a,s,k,e,t]).
word(basketball, [b,a,s,k,e,t,b,a,l,l]).
word(bathroom, [b,a,t,h,r,o,o,m]).
word(battery, [b,a,t,t,e,r,y]).
word(battle, [b,a,t,t,l,e]).
word(be, [b,e]).
word(beach, [b,e,a,c,h]).
word(bean, [b,e,a,n]).
word(bear, [b,e,a,r]).
word(beat, [b,e,a,t]).
word(beautiful, [b,e,a,u,t,i,f,u,l]).
word(beauty, [b,e,a,u,t,y]).
word(because, [b,e,c,a,u,s,e]).
word(become, [b,e,c,o,m,e]).
word(bed, [b,e,d]).
word(bedroom, [b,e,d,r,o,o,m]).
word(beer, [b,e,e,r]).
word(before, [b,e,f,o,r,e]).
word(begin, [b,e,g,i,n]).
word(beginning, [b,e,g,i,n,n,i,n,g]).
word(behavior, [b,e,h,a,v,i,o,r]).
word(behind, [b,e,h,i,n,d]).
word(being, [b,e,i,n,g]).
word(belief, [b,e,l,i,e,f]).
word(believe, [b,e,l,i,e,v,e]).
word(bell, [b,e,l,l]).
word(belong, [b,e,l,o,n,g]).
word(below, [b,e,l,o,w]).
word(belt, [b,e,l,t]).
word(bench, [b,e,n,c,h]).
word(bend, [b,e,n,d]).
word(beneath, [b,e,n,e,a,t,h]).
word(benefit, [b,e,n,e,f,i,t]).
word(beside, [b,e,s,i,d,e]).
word(besides, [b,e,s,i,d,e,s]).
word(best, [b,e,s,t]).
word(bet, [b,e,t]).
word(better, [b,e,t,t,e,r]).
word(between, [b,e,t,w,e,e,n]).
word(beyond, [b,e,y,o,n,d]).
word(bible, [b,i,b,l,e]).
word(big, [b,i,g]).
word(bike, [b,i,k,e]).
word(bill, [b,i,l,l]).
word(billion, [b,i,l,l,i,o,n]).
word(bind, [b,i,n,d]).
word(biological, [b,i,o,l,o,g,i,c,a,l]).
word(bird, [b,i,r,d]).
word(birth, [b,i,r,t,h]).
word(birthday, [b,i,r,t,h,d,a,y]).
word(bit, [b,i,t]).
word(bite, [b,i,t,e]).
word(black, [b,l,a,c,k]).
word(blade, [b,l,a,d,e]).
word(blame, [b,l,a,m,e]).
word(blanket, [b,l,a,n,k,e,t]).
word(blind, [b,l,i,n,d]).
word(block, [b,l,o,c,k]).
word(blood, [b,l,o,o,d]).
word(blow, [b,l,o,w]).
word(blue, [b,l,u,e]).
word(board, [b,o,a,r,d]).
word(boat, [b,o,a,t]).
word(body, [b,o,d,y]).
word(bomb, [b,o,m,b]).
word(bombing, [b,o,m,b,i,n,g]).
word(bond, [b,o,n,d]).
word(bone, [b,o,n,e]).
word(book, [b,o,o,k]).
word(boom, [b,o,o,m]).
word(boot, [b,o,o,t]).
word(border, [b,o,r,d,e,r]).
word(born, [b,o,r,n]).
word(borrow, [b,o,r,r,o,w]).
word(boss, [b,o,s,s]).
word(both, [b,o,t,h]).
word(bother, [b,o,t,h,e,r]).
word(bottle, [b,o,t,t,l,e]).
word(bottom, [b,o,t,t,o,m]).
word(boundary, [b,o,u,n,d,a,r,y]).
word(bowl, [b,o,w,l]).
word(box, [b,o,x]).
word(boy, [b,o,y]).
word(boyfriend, [b,o,y,f,r,i,e,n,d]).
word(brain, [b,r,a,i,n]).
word(branch, [b,r,a,n,c,h]).
word(brand, [b,r,a,n,d]).
word(bread, [b,r,e,a,d]).
word(break, [b,r,e,a,k]).
word(breakfast, [b,r,e,a,k,f,a,s,t]).
word(breast, [b,r,e,a,s,t]).
word(breath, [b,r,e,a,t,h]).
word(breathe, [b,r,e,a,t,h,e]).
word(brick, [b,r,i,c,k]).
word(bridge, [b,r,i,d,g,e]).
word(brief, [b,r,i,e,f]).
word(briefly, [b,r,i,e,f,l,y]).
word(bright, [b,r,i,g,h,t]).
word(brilliant, [b,r,i,l,l,i,a,n,t]).
word(bring, [b,r,i,n,g]).
word(british, [b,r,i,t,i,s,h]).
word(broad, [b,r,o,a,d]).
word(broken, [b,r,o,k,e,n]).
word(brother, [b,r,o,t,h,e,r]).
word(brown, [b,r,o,w,n]).
word(brush, [b,r,u,s,h]).
word(buck, [b,u,c,k]).
word(budget, [b,u,d,g,e,t]).
word(build, [b,u,i,l,d]).
word(building, [b,u,i,l,d,i,n,g]).
word(bullet, [b,u,l,l,e,t]).
word(bunch, [b,u,n,c,h]).
word(burden, [b,u,r,d,e,n]).
word(burn, [b,u,r,n]).
word(bury, [b,u,r,y]).
word(bus, [b,u,s]).
word(business, [b,u,s,i,n,e,s,s]).
word(busy, [b,u,s,y]).
word(but, [b,u,t]).
word(butter, [b,u,t,t,e,r]).
word(button, [b,u,t,t,o,n]).
word(buy, [b,u,y]).
word(buyer, [b,u,y,e,r]).
word(by, [b,y]).
word(cabin, [c,a,b,i,n]).
word(cabinet, [c,a,b,i,n,e,t]).
word(cable, [c,a,b,l,e]).
word(cake, [c,a,k,e]).
word(calculate, [c,a,l,c,u,l,a,t,e]).
word(call, [c,a,l,l]).
word(camera, [c,a,m,e,r,a]).
word(camp, [c,a,m,p]).
word(campaign, [c,a,m,p,a,i,g,n]).
word(campus, [c,a,m,p,u,s]).
word(can, [c,a,n]).
word(canadian, [c,a,n,a,d,i,a,n]).
word(cancer, [c,a,n,c,e,r]).
word(candidate, [c,a,n,d,i,d,a,t,e]).
word(cap, [c,a,p]).
word(capability, [c,a,p,a,b,i,l,i,t,y]).
word(capable, [c,a,p,a,b,l,e]).
word(capacity, [c,a,p,a,c,i,t,y]).
word(capital, [c,a,p,i,t,a,l]).
word(captain, [c,a,p,t,a,i,n]).
word(capture, [c,a,p,t,u,r,e]).
word(car, [c,a,r]).
word(carbon, [c,a,r,b,o,n]).
word(card, [c,a,r,d]).
word(care, [c,a,r,e]).
word(career, [c,a,r,e,e,r]).
word(careful, [c,a,r,e,f,u,l]).
word(carefully, [c,a,r,e,f,u,l,l,y]).
word(carrier, [c,a,r,r,i,e,r]).
word(carry, [c,a,r,r,y]).
word(case, [c,a,s,e]).
word(cash, [c,a,s,h]).
word(cast, [c,a,s,t]).
word(cat, [c,a,t]).
word(catch, [c,a,t,c,h]).
word(category, [c,a,t,e,g,o,r,y]).
word(catholic, [c,a,t,h,o,l,i,c]).
word(cause, [c,a,u,s,e]).
word(ceiling, [c,e,i,l,i,n,g]).
word(celebrate, [c,e,l,e,b,r,a,t,e]).
word(celebration, [c,e,l,e,b,r,a,t,i,o,n]).
word(celebrity, [c,e,l,e,b,r,i,t,y]).
word(cell, [c,e,l,l]).
word(center, [c,e,n,t,e,r]).
word(central, [c,e,n,t,r,a,l]).
word(century, [c,e,n,t,u,r,y]).
word(ceo, [c,e,o]).
word(ceremony, [c,e,r,e,m,o,n,y]).
word(certain, [c,e,r,t,a,i,n]).
word(certainly, [c,e,r,t,a,i,n,l,y]).
word(chain, [c,h,a,i,n]).
word(chair, [c,h,a,i,r]).
word(chairman, [c,h,a,i,r,m,a,n]).
word(challenge, [c,h,a,l,l,e,n,g,e]).
word(chamber, [c,h,a,m,b,e,r]).
word(champion, [c,h,a,m,p,i,o,n]).
word(championship, [c,h,a,m,p,i,o,n,s,h,i,p]).
word(chance, [c,h,a,n,c,e]).
word(change, [c,h,a,n,g,e]).
word(changing, [c,h,a,n,g,i,n,g]).
word(channel, [c,h,a,n,n,e,l]).
word(chapter, [c,h,a,p,t,e,r]).
word(character, [c,h,a,r,a,c,t,e,r]).
word(characteristic, [c,h,a,r,a,c,t,e,r,i,s,t,i,c]).
word(characterize, [c,h,a,r,a,c,t,e,r,i,z,e]).
word(charge, [c,h,a,r,g,e]).
word(charity, [c,h,a,r,i,t,y]).
word(chart, [c,h,a,r,t]).
word(chase, [c,h,a,s,e]).
word(cheap, [c,h,e,a,p]).
word(check, [c,h,e,c,k]).
word(cheek, [c,h,e,e,k]).
word(cheese, [c,h,e,e,s,e]).
word(chef, [c,h,e,f]).
word(chemical, [c,h,e,m,i,c,a,l]).
word(chest, [c,h,e,s,t]).
word(chicken, [c,h,i,c,k,e,n]).
word(chief, [c,h,i,e,f]).
word(child, [c,h,i,l,d]).
word(childhood, [c,h,i,l,d,h,o,o,d]).
word(chinese, [c,h,i,n,e,s,e]).
word(chip, [c,h,i,p]).
word(chocolate, [c,h,o,c,o,l,a,t,e]).
word(choice, [c,h,o,i,c,e]).
word(cholesterol, [c,h,o,l,e,s,t,e,r,o,l]).
word(choose, [c,h,o,o,s,e]).
word(christian, [c,h,r,i,s,t,i,a,n]).
word(christmas, [c,h,r,i,s,t,m,a,s]).
word(church, [c,h,u,r,c,h]).
word(cigarette, [c,i,g,a,r,e,t,t,e]).
word(circle, [c,i,r,c,l,e]).
word(circumstance, [c,i,r,c,u,m,s,t,a,n,c,e]).
word(cite, [c,i,t,e]).
word(citizen, [c,i,t,i,z,e,n]).
word(city, [c,i,t,y]).
word(civil, [c,i,v,i,l]).
word(civilian, [c,i,v,i,l,i,a,n]).
word(claim, [c,l,a,i,m]).
word(class, [c,l,a,s,s]).
word(classic, [c,l,a,s,s,i,c]).
word(classroom, [c,l,a,s,s,r,o,o,m]).
word(clean, [c,l,e,a,n]).
word(clear, [c,l,e,a,r]).
word(clearly, [c,l,e,a,r,l,y]).
word(client, [c,l,i,e,n,t]).
word(climate, [c,l,i,m,a,t,e]).
word(climb, [c,l,i,m,b]).
word(clinic, [c,l,i,n,i,c]).
word(clinical, [c,l,i,n,i,c,a,l]).
word(clock, [c,l,o,c,k]).
word(close, [c,l,o,s,e]).
word(closely, [c,l,o,s,e,l,y]).
word(closer, [c,l,o,s,e,r]).
word(clothes, [c,l,o,t,h,e,s]).
word(clothing, [c,l,o,t,h,i,n,g]).
word(cloud, [c,l,o,u,d]).
word(club, [c,l,u,b]).
word(clue, [c,l,u,e]).
word(cluster, [c,l,u,s,t,e,r]).
word(coach, [c,o,a,c,h]).
word(coal, [c,o,a,l]).
word(coalition, [c,o,a,l,i,t,i,o,n]).
word(coast, [c,o,a,s,t]).
word(coat, [c,o,a,t]).
word(code, [c,o,d,e]).
word(coffee, [c,o,f,f,e,e]).
word(cognitive, [c,o,g,n,i,t,i,v,e]).
word(cold, [c,o,l,d]).
word(collapse, [c,o,l,l,a,p,s,e]).
word(colleague, [c,o,l,l,e,a,g,u,e]).
word(collect, [c,o,l,l,e,c,t]).
word(collection, [c,o,l,l,e,c,t,i,o,n]).
word(collective, [c,o,l,l,e,c,t,i,v,e]).
word(college, [c,o,l,l,e,g,e]).
word(colonial, [c,o,l,o,n,i,a,l]).
word(color, [c,o,l,o,r]).
word(column, [c,o,l,u,m,n]).
word(combination, [c,o,m,b,i,n,a,t,i,o,n]).
word(combine, [c,o,m,b,i,n,e]).
word(come, [c,o,m,e]).
word(comedy, [c,o,m,e,d,y]).
word(comfort, [c,o,m,f,o,r,t]).
word(comfortable, [c,o,m,f,o,r,t,a,b,l,e]).
word(command, [c,o,m,m,a,n,d]).
word(commander, [c,o,m,m,a,n,d,e,r]).
word(comment, [c,o,m,m,e,n,t]).
word(commercial, [c,o,m,m,e,r,c,i,a,l]).
word(commission, [c,o,m,m,i,s,s,i,o,n]).
word(commit, [c,o,m,m,i,t]).
word(commitment, [c,o,m,m,i,t,m,e,n,t]).
word(committee, [c,o,m,m,i,t,t,e,e]).
word(common, [c,o,m,m,o,n]).
word(communicate, [c,o,m,m,u,n,i,c,a,t,e]).
word(communication, [c,o,m,m,u,n,i,c,a,t,i,o,n]).
word(community, [c,o,m,m,u,n,i,t,y]).
word(company, [c,o,m,p,a,n,y]).
word(compare, [c,o,m,p,a,r,e]).
word(comparison, [c,o,m,p,a,r,i,s,o,n]).
word(compete, [c,o,m,p,e,t,e]).
word(competition, [c,o,m,p,e,t,i,t,i,o,n]).
word(competitive, [c,o,m,p,e,t,i,t,i,v,e]).
word(competitor, [c,o,m,p,e,t,i,t,o,r]).
word(complain, [c,o,m,p,l,a,i,n]).
word(complaint, [c,o,m,p,l,a,i,n,t]).
word(complete, [c,o,m,p,l,e,t,e]).
word(completely, [c,o,m,p,l,e,t,e,l,y]).
word(complex, [c,o,m,p,l,e,x]).
word(complicated, [c,o,m,p,l,i,c,a,t,e,d]).
word(component, [c,o,m,p,o,n,e,n,t]).
word(compose, [c,o,m,p,o,s,e]).
word(composition, [c,o,m,p,o,s,i,t,i,o,n]).
word(comprehensive, [c,o,m,p,r,e,h,e,n,s,i,v,e]).
word(computer, [c,o,m,p,u,t,e,r]).
word(concentrate, [c,o,n,c,e,n,t,r,a,t,e]).
word(concentration, [c,o,n,c,e,n,t,r,a,t,i,o,n]).
word(concept, [c,o,n,c,e,p,t]).
word(concern, [c,o,n,c,e,r,n]).
word(concerned, [c,o,n,c,e,r,n,e,d]).
word(concert, [c,o,n,c,e,r,t]).
word(conclude, [c,o,n,c,l,u,d,e]).
word(conclusion, [c,o,n,c,l,u,s,i,o,n]).
word(concrete, [c,o,n,c,r,e,t,e]).
word(condition, [c,o,n,d,i,t,i,o,n]).
word(conduct, [c,o,n,d,u,c,t]).
word(conference, [c,o,n,f,e,r,e,n,c,e]).
word(confidence, [c,o,n,f,i,d,e,n,c,e]).
word(confident, [c,o,n,f,i,d,e,n,t]).
word(confirm, [c,o,n,f,i,r,m]).
word(conflict, [c,o,n,f,l,i,c,t]).
word(confront, [c,o,n,f,r,o,n,t]).
word(confusion, [c,o,n,f,u,s,i,o,n]).
word(congress, [c,o,n,g,r,e,s,s]).
word(congressional, [c,o,n,g,r,e,s,s,i,o,n,a,l]).
word(connect, [c,o,n,n,e,c,t]).
word(connection, [c,o,n,n,e,c,t,i,o,n]).
word(consciousness, [c,o,n,s,c,i,o,u,s,n,e,s,s]).
word(consensus, [c,o,n,s,e,n,s,u,s]).
word(consequence, [c,o,n,s,e,q,u,e,n,c,e]).
word(conservative, [c,o,n,s,e,r,v,a,t,i,v,e]).
word(consider, [c,o,n,s,i,d,e,r]).
word(considerable, [c,o,n,s,i,d,e,r,a,b,l,e]).
word(consideration, [c,o,n,s,i,d,e,r,a,t,i,o,n]).
word(consist, [c,o,n,s,i,s,t]).
word(consistent, [c,o,n,s,i,s,t,e,n,t]).
word(constant, [c,o,n,s,t,a,n,t]).
word(constantly, [c,o,n,s,t,a,n,t,l,y]).
word(constitute, [c,o,n,s,t,i,t,u,t,e]).
word(constitutional, [c,o,n,s,t,i,t,u,t,i,o,n,a,l]).
word(construct, [c,o,n,s,t,r,u,c,t]).
word(construction, [c,o,n,s,t,r,u,c,t,i,o,n]).
word(consultant, [c,o,n,s,u,l,t,a,n,t]).
word(consume, [c,o,n,s,u,m,e]).
word(consumer, [c,o,n,s,u,m,e,r]).
word(consumption, [c,o,n,s,u,m,p,t,i,o,n]).
word(contact, [c,o,n,t,a,c,t]).
word(contain, [c,o,n,t,a,i,n]).
word(container, [c,o,n,t,a,i,n,e,r]).
word(contemporary, [c,o,n,t,e,m,p,o,r,a,r,y]).
word(content, [c,o,n,t,e,n,t]).
word(contest, [c,o,n,t,e,s,t]).
word(context, [c,o,n,t,e,x,t]).
word(continue, [c,o,n,t,i,n,u,e]).
word(continued, [c,o,n,t,i,n,u,e,d]).
word(contract, [c,o,n,t,r,a,c,t]).
word(contrast, [c,o,n,t,r,a,s,t]).
word(contribute, [c,o,n,t,r,i,b,u,t,e]).
word(contribution, [c,o,n,t,r,i,b,u,t,i,o,n]).
word(control, [c,o,n,t,r,o,l]).
word(controversial, [c,o,n,t,r,o,v,e,r,s,i,a,l]).
word(controversy, [c,o,n,t,r,o,v,e,r,s,y]).
word(convention, [c,o,n,v,e,n,t,i,o,n]).
word(conventional, [c,o,n,v,e,n,t,i,o,n,a,l]).
word(conversation, [c,o,n,v,e,r,s,a,t,i,o,n]).
word(convert, [c,o,n,v,e,r,t]).
word(conviction, [c,o,n,v,i,c,t,i,o,n]).
word(convince, [c,o,n,v,i,n,c,e]).
word(cook, [c,o,o,k]).
word(cookie, [c,o,o,k,i,e]).
word(cooking, [c,o,o,k,i,n,g]).
word(cool, [c,o,o,l]).
word(cooperation, [c,o,o,p,e,r,a,t,i,o,n]).
word(cop, [c,o,p]).
word(cope, [c,o,p,e]).
word(copy, [c,o,p,y]).
word(core, [c,o,r,e]).
word(corn, [c,o,r,n]).
word(corner, [c,o,r,n,e,r]).
word(corporate, [c,o,r,p,o,r,a,t,e]).
word(corporation, [c,o,r,p,o,r,a,t,i,o,n]).
word(correct, [c,o,r,r,e,c,t]).
word(correspondent, [c,o,r,r,e,s,p,o,n,d,e,n,t]).
word(cost, [c,o,s,t]).
word(cotton, [c,o,t,t,o,n]).
word(couch, [c,o,u,c,h]).
word(could, [c,o,u,l,d]).
word(council, [c,o,u,n,c,i,l]).
word(counselor, [c,o,u,n,s,e,l,o,r]).
word(count, [c,o,u,n,t]).
word(counter, [c,o,u,n,t,e,r]).
word(country, [c,o,u,n,t,r,y]).
word(county, [c,o,u,n,t,y]).
word(couple, [c,o,u,p,l,e]).
word(courage, [c,o,u,r,a,g,e]).
word(course, [c,o,u,r,s,e]).
word(court, [c,o,u,r,t]).
word(cousin, [c,o,u,s,i,n]).
word(cover, [c,o,v,e,r]).
word(coverage, [c,o,v,e,r,a,g,e]).
word(cow, [c,o,w]).
word(crack, [c,r,a,c,k]).
word(craft, [c,r,a,f,t]).
word(crash, [c,r,a,s,h]).
word(crazy, [c,r,a,z,y]).
word(cream, [c,r,e,a,m]).
word(create, [c,r,e,a,t,e]).
word(creation, [c,r,e,a,t,i,o,n]).
word(creative, [c,r,e,a,t,i,v,e]).
word(creature, [c,r,e,a,t,u,r,e]).
word(credit, [c,r,e,d,i,t]).
word(crew, [c,r,e,w]).
word(crime, [c,r,i,m,e]).
word(criminal, [c,r,i,m,i,n,a,l]).
word(crisis, [c,r,i,s,i,s]).
word(criteria, [c,r,i,t,e,r,i,a]).
word(critic, [c,r,i,t,i,c]).
word(critical, [c,r,i,t,i,c,a,l]).
word(criticism, [c,r,i,t,i,c,i,s,m]).
word(criticize, [c,r,i,t,i,c,i,z,e]).
word(crop, [c,r,o,p]).
word(cross, [c,r,o,s,s]).
word(crowd, [c,r,o,w,d]).
word(crucial, [c,r,u,c,i,a,l]).
word(cry, [c,r,y]).
word(cultural, [c,u,l,t,u,r,a,l]).
word(culture, [c,u,l,t,u,r,e]).
word(cup, [c,u,p]).
word(curious, [c,u,r,i,o,u,s]).
word(current, [c,u,r,r,e,n,t]).
word(currently, [c,u,r,r,e,n,t,l,y]).
word(curriculum, [c,u,r,r,i,c,u,l,u,m]).
word(custom, [c,u,s,t,o,m]).
word(customer, [c,u,s,t,o,m,e,r]).
word(cut, [c,u,t]).
word(cycle, [c,y,c,l,e]).
word(dad, [d,a,d]).
word(daily, [d,a,i,l,y]).
word(damage, [d,a,m,a,g,e]).
word(dance, [d,a,n,c,e]).
word(danger, [d,a,n,g,e,r]).
word(dangerous, [d,a,n,g,e,r,o,u,s]).
word(dare, [d,a,r,e]).
word(dark, [d,a,r,k]).
word(darkness, [d,a,r,k,n,e,s,s]).
word(data, [d,a,t,a]).
word(date, [d,a,t,e]).
word(daughter, [d,a,u,g,h,t,e,r]).
word(day, [d,a,y]).
word(dead, [d,e,a,d]).
word(deal, [d,e,a,l]).
word(dealer, [d,e,a,l,e,r]).
word(dear, [d,e,a,r]).
word(death, [d,e,a,t,h]).
word(debate, [d,e,b,a,t,e]).
word(debt, [d,e,b,t]).
word(decade, [d,e,c,a,d,e]).
word(decide, [d,e,c,i,d,e]).
word(decision, [d,e,c,i,s,i,o,n]).
word(deck, [d,e,c,k]).
word(declare, [d,e,c,l,a,r,e]).
word(decline, [d,e,c,l,i,n,e]).
word(decrease, [d,e,c,r,e,a,s,e]).
word(deep, [d,e,e,p]).
word(deeply, [d,e,e,p,l,y]).
word(deer, [d,e,e,r]).
word(defeat, [d,e,f,e,a,t]).
word(defend, [d,e,f,e,n,d]).
word(defendant, [d,e,f,e,n,d,a,n,t]).
word(defense, [d,e,f,e,n,s,e]).
word(defensive, [d,e,f,e,n,s,i,v,e]).
word(deficit, [d,e,f,i,c,i,t]).
word(define, [d,e,f,i,n,e]).
word(definitely, [d,e,f,i,n,i,t,e,l,y]).
word(definition, [d,e,f,i,n,i,t,i,o,n]).
word(degree, [d,e,g,r,e,e]).
word(delay, [d,e,l,a,y]).
word(deliver, [d,e,l,i,v,e,r]).
word(delivery, [d,e,l,i,v,e,r,y]).
word(demand, [d,e,m,a,n,d]).
word(democracy, [d,e,m,o,c,r,a,c,y]).
word(democrat, [d,e,m,o,c,r,a,t]).
word(democratic, [d,e,m,o,c,r,a,t,i,c]).
word(demonstrate, [d,e,m,o,n,s,t,r,a,t,e]).
word(demonstration, [d,e,m,o,n,s,t,r,a,t,i,o,n]).
word(deny, [d,e,n,y]).
word(department, [d,e,p,a,r,t,m,e,n,t]).
word(depend, [d,e,p,e,n,d]).
word(dependent, [d,e,p,e,n,d,e,n,t]).
word(depending, [d,e,p,e,n,d,i,n,g]).
word(depict, [d,e,p,i,c,t]).
word(depression, [d,e,p,r,e,s,s,i,o,n]).
word(depth, [d,e,p,t,h]).
word(deputy, [d,e,p,u,t,y]).
word(derive, [d,e,r,i,v,e]).
word(describe, [d,e,s,c,r,i,b,e]).
word(description, [d,e,s,c,r,i,p,t,i,o,n]).
word(desert, [d,e,s,e,r,t]).
word(deserve, [d,e,s,e,r,v,e]).
word(design, [d,e,s,i,g,n]).
word(designer, [d,e,s,i,g,n,e,r]).
word(desire, [d,e,s,i,r,e]).
word(desk, [d,e,s,k]).
word(desperate, [d,e,s,p,e,r,a,t,e]).
word(despite, [d,e,s,p,i,t,e]).
word(destroy, [d,e,s,t,r,o,y]).
word(destruction, [d,e,s,t,r,u,c,t,i,o,n]).
word(detail, [d,e,t,a,i,l]).
word(detailed, [d,e,t,a,i,l,e,d]).
word(detect, [d,e,t,e,c,t]).
word(determine, [d,e,t,e,r,m,i,n,e]).
word(develop, [d,e,v,e,l,o,p]).
word(developing, [d,e,v,e,l,o,p,i,n,g]).
word(development, [d,e,v,e,l,o,p,m,e,n,t]).
word(device, [d,e,v,i,c,e]).
word(devote, [d,e,v,o,t,e]).
word(dialogue, [d,i,a,l,o,g,u,e]).
word(die, [d,i,e]).
word(diet, [d,i,e,t]).
word(differ, [d,i,f,f,e,r]).
word(difference, [d,i,f,f,e,r,e,n,c,e]).
word(different, [d,i,f,f,e,r,e,n,t]).
word(differently, [d,i,f,f,e,r,e,n,t,l,y]).
word(difficult, [d,i,f,f,i,c,u,l,t]).
word(difficulty, [d,i,f,f,i,c,u,l,t,y]).
word(dig, [d,i,g]).
word(digital, [d,i,g,i,t,a,l]).
word(dimension, [d,i,m,e,n,s,i,o,n]).
word(dining, [d,i,n,i,n,g]).
word(dinner, [d,i,n,n,e,r]).
word(direct, [d,i,r,e,c,t]).
word(direction, [d,i,r,e,c,t,i,o,n]).
word(directly, [d,i,r,e,c,t,l,y]).
word(director, [d,i,r,e,c,t,o,r]).
word(dirt, [d,i,r,t]).
word(dirty, [d,i,r,t,y]).
word(disability, [d,i,s,a,b,i,l,i,t,y]).
word(disagree, [d,i,s,a,g,r,e,e]).
word(disappear, [d,i,s,a,p,p,e,a,r]).
word(disaster, [d,i,s,a,s,t,e,r]).
word(discipline, [d,i,s,c,i,p,l,i,n,e]).
word(discourse, [d,i,s,c,o,u,r,s,e]).
word(discover, [d,i,s,c,o,v,e,r]).
word(discovery, [d,i,s,c,o,v,e,r,y]).
word(discrimination, [d,i,s,c,r,i,m,i,n,a,t,i,o,n]).
word(discuss, [d,i,s,c,u,s,s]).
word(discussion, [d,i,s,c,u,s,s,i,o,n]).
word(disease, [d,i,s,e,a,s,e]).
word(dish, [d,i,s,h]).
word(dismiss, [d,i,s,m,i,s,s]).
word(disorder, [d,i,s,o,r,d,e,r]).
word(display, [d,i,s,p,l,a,y]).
word(dispute, [d,i,s,p,u,t,e]).
word(distance, [d,i,s,t,a,n,c,e]).
word(distant, [d,i,s,t,a,n,t]).
word(distinct, [d,i,s,t,i,n,c,t]).
word(distinction, [d,i,s,t,i,n,c,t,i,o,n]).
word(distinguish, [d,i,s,t,i,n,g,u,i,s,h]).
word(distribute, [d,i,s,t,r,i,b,u,t,e]).
word(distribution, [d,i,s,t,r,i,b,u,t,i,o,n]).
word(district, [d,i,s,t,r,i,c,t]).
word(diverse, [d,i,v,e,r,s,e]).
word(diversity, [d,i,v,e,r,s,i,t,y]).
word(divide, [d,i,v,i,d,e]).
word(division, [d,i,v,i,s,i,o,n]).
word(divorce, [d,i,v,o,r,c,e]).
word(dna, [d,n,a]).
word(do, [d,o]).
word(doctor, [d,o,c,t,o,r]).
word(document, [d,o,c,u,m,e,n,t]).
word(dog, [d,o,g]).
word(domestic, [d,o,m,e,s,t,i,c]).
word(dominant, [d,o,m,i,n,a,n,t]).
word(dominate, [d,o,m,i,n,a,t,e]).
word(door, [d,o,o,r]).
word(double, [d,o,u,b,l,e]).
word(doubt, [d,o,u,b,t]).
word(down, [d,o,w,n]).
word(downtown, [d,o,w,n,t,o,w,n]).
word(dozen, [d,o,z,e,n]).
word(draft, [d,r,a,f,t]).
word(drag, [d,r,a,g]).
word(drama, [d,r,a,m,a]).
word(dramatic, [d,r,a,m,a,t,i,c]).
word(dramatically, [d,r,a,m,a,t,i,c,a,l,l,y]).
word(draw, [d,r,a,w]).
word(drawing, [d,r,a,w,i,n,g]).
word(dream, [d,r,e,a,m]).
word(dress, [d,r,e,s,s]).
word(drink, [d,r,i,n,k]).
word(drive, [d,r,i,v,e]).
word(driver, [d,r,i,v,e,r]).
word(drop, [d,r,o,p]).
word(drug, [d,r,u,g]).
word(dry, [d,r,y]).
word(due, [d,u,e]).
word(during, [d,u,r,i,n,g]).
word(dust, [d,u,s,t]).
word(duty, [d,u,t,y]).
word(each, [e,a,c,h]).
word(eager, [e,a,g,e,r]).
word(ear, [e,a,r]).
word(early, [e,a,r,l,y]).
word(earn, [e,a,r,n]).
word(earnings, [e,a,r,n,i,n,g,s]).
word(earth, [e,a,r,t,h]).
word(ease, [e,a,s,e]).
word(easily, [e,a,s,i,l,y]).
word(east, [e,a,s,t]).
word(eastern, [e,a,s,t,e,r,n]).
word(easy, [e,a,s,y]).
word(eat, [e,a,t]).
word(economic, [e,c,o,n,o,m,i,c]).
word(economics, [e,c,o,n,o,m,i,c,s]).
word(economist, [e,c,o,n,o,m,i,s,t]).
word(economy, [e,c,o,n,o,m,y]).
word(edge, [e,d,g,e]).
word(edition, [e,d,i,t,i,o,n]).
word(editor, [e,d,i,t,o,r]).
word(educate, [e,d,u,c,a,t,e]).
word(education, [e,d,u,c,a,t,i,o,n]).
word(educational, [e,d,u,c,a,t,i,o,n,a,l]).
word(educator, [e,d,u,c,a,t,o,r]).
word(effect, [e,f,f,e,c,t]).
word(effective, [e,f,f,e,c,t,i,v,e]).
word(effectively, [e,f,f,e,c,t,i,v,e,l,y]).
word(efficiency, [e,f,f,i,c,i,e,n,c,y]).
word(efficient, [e,f,f,i,c,i,e,n,t]).
word(effort, [e,f,f,o,r,t]).
word(egg, [e,g,g]).
word(eight, [e,i,g,h,t]).
word(either, [e,i,t,h,e,r]).
word(elderly, [e,l,d,e,r,l,y]).
word(elect, [e,l,e,c,t]).
word(election, [e,l,e,c,t,i,o,n]).
word(electric, [e,l,e,c,t,r,i,c]).
word(electricity, [e,l,e,c,t,r,i,c,i,t,y]).
word(electronic, [e,l,e,c,t,r,o,n,i,c]).
word(element, [e,l,e,m,e,n,t]).
word(elementary, [e,l,e,m,e,n,t,a,r,y]).
word(eliminate, [e,l,i,m,i,n,a,t,e]).
word(elite, [e,l,i,t,e]).
word(else, [e,l,s,e]).
word(elsewhere, [e,l,s,e,w,h,e,r,e]).
word(embrace, [e,m,b,r,a,c,e]).
word(emerge, [e,m,e,r,g,e]).
word(emergency, [e,m,e,r,g,e,n,c,y]).
word(emission, [e,m,i,s,s,i,o,n]).
word(emotion, [e,m,o,t,i,o,n]).
word(emotional, [e,m,o,t,i,o,n,a,l]).
word(emphasis, [e,m,p,h,a,s,i,s]).
word(emphasize, [e,m,p,h,a,s,i,z,e]).
word(employ, [e,m,p,l,o,y]).
word(employee, [e,m,p,l,o,y,e,e]).
word(employer, [e,m,p,l,o,y,e,r]).
word(employment, [e,m,p,l,o,y,m,e,n,t]).
word(empty, [e,m,p,t,y]).
word(enable, [e,n,a,b,l,e]).
word(encounter, [e,n,c,o,u,n,t,e,r]).
word(encourage, [e,n,c,o,u,r,a,g,e]).
word(end, [e,n,d]).
word(enemy, [e,n,e,m,y]).
word(energy, [e,n,e,r,g,y]).
word(enforcement, [e,n,f,o,r,c,e,m,e,n,t]).
word(engage, [e,n,g,a,g,e]).
word(engine, [e,n,g,i,n,e]).
word(engineer, [e,n,g,i,n,e,e,r]).
word(engineering, [e,n,g,i,n,e,e,r,i,n,g]).
word(english, [e,n,g,l,i,s,h]).
word(enhance, [e,n,h,a,n,c,e]).
word(enjoy, [e,n,j,o,y]).
word(enormous, [e,n,o,r,m,o,u,s]).
word(enough, [e,n,o,u,g,h]).
word(ensure, [e,n,s,u,r,e]).
word(enter, [e,n,t,e,r]).
word(enterprise, [e,n,t,e,r,p,r,i,s,e]).
word(entertainment, [e,n,t,e,r,t,a,i,n,m,e,n,t]).
word(entire, [e,n,t,i,r,e]).
word(entirely, [e,n,t,i,r,e,l,y]).
word(entrance, [e,n,t,r,a,n,c,e]).
word(entry, [e,n,t,r,y]).
word(environment, [e,n,v,i,r,o,n,m,e,n,t]).
word(environmental, [e,n,v,i,r,o,n,m,e,n,t,a,l]).
word(episode, [e,p,i,s,o,d,e]).
word(equal, [e,q,u,a,l]).
word(equally, [e,q,u,a,l,l,y]).
word(equipment, [e,q,u,i,p,m,e,n,t]).
word(era, [e,r,a]).
word(error, [e,r,r,o,r]).
word(escape, [e,s,c,a,p,e]).
word(especially, [e,s,p,e,c,i,a,l,l,y]).
word(essay, [e,s,s,a,y]).
word(essential, [e,s,s,e,n,t,i,a,l]).
word(essentially, [e,s,s,e,n,t,i,a,l,l,y]).
word(establish, [e,s,t,a,b,l,i,s,h]).
word(establishment, [e,s,t,a,b,l,i,s,h,m,e,n,t]).
word(estate, [e,s,t,a,t,e]).
word(estimate, [e,s,t,i,m,a,t,e]).
word(etc, [e,t,c]).
word(ethics, [e,t,h,i,c,s]).
word(ethnic, [e,t,h,n,i,c]).
word(european, [e,u,r,o,p,e,a,n]).
word(evaluate, [e,v,a,l,u,a,t,e]).
word(evaluation, [e,v,a,l,u,a,t,i,o,n]).
word(even, [e,v,e,n]).
word(evening, [e,v,e,n,i,n,g]).
word(event, [e,v,e,n,t]).
word(eventually, [e,v,e,n,t,u,a,l,l,y]).
word(ever, [e,v,e,r]).
word(every, [e,v,e,r,y]).
word(everybody, [e,v,e,r,y,b,o,d,y]).
word(everyday, [e,v,e,r,y,d,a,y]).
word(everyone, [e,v,e,r,y,o,n,e]).
word(everything, [e,v,e,r,y,t,h,i,n,g]).
word(everywhere, [e,v,e,r,y,w,h,e,r,e]).
word(evidence, [e,v,i,d,e,n,c,e]).
word(evolution, [e,v,o,l,u,t,i,o,n]).
word(evolve, [e,v,o,l,v,e]).
word(exact, [e,x,a,c,t]).
word(exactly, [e,x,a,c,t,l,y]).
word(examination, [e,x,a,m,i,n,a,t,i,o,n]).
word(examine, [e,x,a,m,i,n,e]).
word(example, [e,x,a,m,p,l,e]).
word(exceed, [e,x,c,e,e,d]).
word(excellent, [e,x,c,e,l,l,e,n,t]).
word(except, [e,x,c,e,p,t]).
word(exception, [e,x,c,e,p,t,i,o,n]).
word(exchange, [e,x,c,h,a,n,g,e]).
word(exciting, [e,x,c,i,t,i,n,g]).
word(executive, [e,x,e,c,u,t,i,v,e]).
word(exercise, [e,x,e,r,c,i,s,e]).
word(exhibit, [e,x,h,i,b,i,t]).
word(exhibition, [e,x,h,i,b,i,t,i,o,n]).
word(exist, [e,x,i,s,t]).
word(existence, [e,x,i,s,t,e,n,c,e]).
word(existing, [e,x,i,s,t,i,n,g]).
word(expand, [e,x,p,a,n,d]).
word(expansion, [e,x,p,a,n,s,i,o,n]).
word(expect, [e,x,p,e,c,t]).
word(expectation, [e,x,p,e,c,t,a,t,i,o,n]).
word(expense, [e,x,p,e,n,s,e]).
word(expensive, [e,x,p,e,n,s,i,v,e]).
word(experience, [e,x,p,e,r,i,e,n,c,e]).
word(experiment, [e,x,p,e,r,i,m,e,n,t]).
word(expert, [e,x,p,e,r,t]).
word(explain, [e,x,p,l,a,i,n]).
word(explanation, [e,x,p,l,a,n,a,t,i,o,n]).
word(explode, [e,x,p,l,o,d,e]).
word(explore, [e,x,p,l,o,r,e]).
word(explosion, [e,x,p,l,o,s,i,o,n]).
word(expose, [e,x,p,o,s,e]).
word(exposure, [e,x,p,o,s,u,r,e]).
word(express, [e,x,p,r,e,s,s]).
word(expression, [e,x,p,r,e,s,s,i,o,n]).
word(extend, [e,x,t,e,n,d]).
word(extension, [e,x,t,e,n,s,i,o,n]).
word(extensive, [e,x,t,e,n,s,i,v,e]).
word(extent, [e,x,t,e,n,t]).
word(external, [e,x,t,e,r,n,a,l]).
word(extra, [e,x,t,r,a]).
word(extraordinary, [e,x,t,r,a,o,r,d,i,n,a,r,y]).
word(extreme, [e,x,t,r,e,m,e]).
word(extremely, [e,x,t,r,e,m,e,l,y]).
word(eye, [e,y,e]).
word(fabric, [f,a,b,r,i,c]).
word(face, [f,a,c,e]).
word(facility, [f,a,c,i,l,i,t,y]).
word(fact, [f,a,c,t]).
word(factor, [f,a,c,t,o,r]).
word(factory, [f,a,c,t,o,r,y]).
word(faculty, [f,a,c,u,l,t,y]).
word(fade, [f,a,d,e]).
word(fail, [f,a,i,l]).
word(failure, [f,a,i,l,u,r,e]).
word(fair, [f,a,i,r]).
word(fairly, [f,a,i,r,l,y]).
word(faith, [f,a,i,t,h]).
word(fall, [f,a,l,l]).
word(false, [f,a,l,s,e]).
word(familiar, [f,a,m,i,l,i,a,r]).
word(family, [f,a,m,i,l,y]).
word(famous, [f,a,m,o,u,s]).
word(fan, [f,a,n]).
word(fantasy, [f,a,n,t,a,s,y]).
word(far, [f,a,r]).
word(farm, [f,a,r,m]).
word(farmer, [f,a,r,m,e,r]).
word(fashion, [f,a,s,h,i,o,n]).
word(fast, [f,a,s,t]).
word(fat, [f,a,t]).
word(fate, [f,a,t,e]).
word(father, [f,a,t,h,e,r]).
word(fault, [f,a,u,l,t]).
word(favor, [f,a,v,o,r]).
word(favorite, [f,a,v,o,r,i,t,e]).
word(fear, [f,e,a,r]).
word(feature, [f,e,a,t,u,r,e]).
word(federal, [f,e,d,e,r,a,l]).
word(fee, [f,e,e]).
word(feed, [f,e,e,d]).
word(feel, [f,e,e,l]).
word(feeling, [f,e,e,l,i,n,g]).
word(fellow, [f,e,l,l,o,w]).
word(female, [f,e,m,a,l,e]).
word(fence, [f,e,n,c,e]).
word(few, [f,e,w]).
word(fewer, [f,e,w,e,r]).
word(fiber, [f,i,b,e,r]).
word(fiction, [f,i,c,t,i,o,n]).
word(field, [f,i,e,l,d]).
word(fifteen, [f,i,f,t,e,e,n]).
word(fifth, [f,i,f,t,h]).
word(fifty, [f,i,f,t,y]).
word(fight, [f,i,g,h,t]).
word(fighter, [f,i,g,h,t,e,r]).
word(fighting, [f,i,g,h,t,i,n,g]).
word(figure, [f,i,g,u,r,e]).
word(file, [f,i,l,e]).
word(fill, [f,i,l,l]).
word(film, [f,i,l,m]).
word(final, [f,i,n,a,l]).
word(finally, [f,i,n,a,l,l,y]).
word(finance, [f,i,n,a,n,c,e]).
word(financial, [f,i,n,a,n,c,i,a,l]).
word(find, [f,i,n,d]).
word(finding, [f,i,n,d,i,n,g]).
word(fine, [f,i,n,e]).
word(finger, [f,i,n,g,e,r]).
word(finish, [f,i,n,i,s,h]).
word(fire, [f,i,r,e]).
word(firm, [f,i,r,m]).
word(first, [f,i,r,s,t]).
word(fish, [f,i,s,h]).
word(fishing, [f,i,s,h,i,n,g]).
word(fit, [f,i,t]).
word(fitness, [f,i,t,n,e,s,s]).
word(five, [f,i,v,e]).
word(fix, [f,i,x]).
word(flag, [f,l,a,g]).
word(flame, [f,l,a,m,e]).
word(flat, [f,l,a,t]).
word(flavor, [f,l,a,v,o,r]).
word(flee, [f,l,e,e]).
word(flesh, [f,l,e,s,h]).
word(flight, [f,l,i,g,h,t]).
word(float, [f,l,o,a,t]).
word(floor, [f,l,o,o,r]).
word(flow, [f,l,o,w]).
word(flower, [f,l,o,w,e,r]).
word(fly, [f,l,y]).
word(focus, [f,o,c,u,s]).
word(folk, [f,o,l,k]).
word(follow, [f,o,l,l,o,w]).
word(following, [f,o,l,l,o,w,i,n,g]).
word(food, [f,o,o,d]).
word(foot, [f,o,o,t]).
word(football, [f,o,o,t,b,a,l,l]).
word(for, [f,o,r]).
word(force, [f,o,r,c,e]).
word(foreign, [f,o,r,e,i,g,n]).
word(forest, [f,o,r,e,s,t]).
word(forever, [f,o,r,e,v,e,r]).
word(forget, [f,o,r,g,e,t]).
word(form, [f,o,r,m]).
word(formal, [f,o,r,m,a,l]).
word(formation, [f,o,r,m,a,t,i,o,n]).
word(former, [f,o,r,m,e,r]).
word(formula, [f,o,r,m,u,l,a]).
word(forth, [f,o,r,t,h]).
word(fortune, [f,o,r,t,u,n,e]).
word(forward, [f,o,r,w,a,r,d]).
word(found, [f,o,u,n,d]).
word(foundation, [f,o,u,n,d,a,t,i,o,n]).
word(founder, [f,o,u,n,d,e,r]).
word(four, [f,o,u,r]).
word(fourth, [f,o,u,r,t,h]).
word(frame, [f,r,a,m,e]).
word(framework, [f,r,a,m,e,w,o,r,k]).
word(free, [f,r,e,e]).
word(freedom, [f,r,e,e,d,o,m]).
word(freeze, [f,r,e,e,z,e]).
word(french, [f,r,e,n,c,h]).
word(frequency, [f,r,e,q,u,e,n,c,y]).
word(frequent, [f,r,e,q,u,e,n,t]).
word(frequently, [f,r,e,q,u,e,n,t,l,y]).
word(fresh, [f,r,e,s,h]).
word(friend, [f,r,i,e,n,d]).
word(friendly, [f,r,i,e,n,d,l,y]).
word(friendship, [f,r,i,e,n,d,s,h,i,p]).
word(from, [f,r,o,m]).
word(front, [f,r,o,n,t]).
word(fruit, [f,r,u,i,t]).
word(frustration, [f,r,u,s,t,r,a,t,i,o,n]).
word(fuel, [f,u,e,l]).
word(full, [f,u,l,l]).
word(fully, [f,u,l,l,y]).
word(fun, [f,u,n]).
word(function, [f,u,n,c,t,i,o,n]).
word(fund, [f,u,n,d]).
word(fundamental, [f,u,n,d,a,m,e,n,t,a,l]).
word(funding, [f,u,n,d,i,n,g]).
word(funeral, [f,u,n,e,r,a,l]).
word(funny, [f,u,n,n,y]).
word(furniture, [f,u,r,n,i,t,u,r,e]).
word(furthermore, [f,u,r,t,h,e,r,m,o,r,e]).
word(future, [f,u,t,u,r,e]).
word(gain, [g,a,i,n]).
word(galaxy, [g,a,l,a,x,y]).
word(gallery, [g,a,l,l,e,r,y]).
word(game, [g,a,m,e]).
word(gang, [g,a,n,g]).
word(gap, [g,a,p]).
word(garage, [g,a,r,a,g,e]).
word(garden, [g,a,r,d,e,n]).
word(garlic, [g,a,r,l,i,c]).
word(gas, [g,a,s]).
word(gate, [g,a,t,e]).
word(gather, [g,a,t,h,e,r]).
word(gay, [g,a,y]).
word(gaze, [g,a,z,e]).
word(gear, [g,e,a,r]).
word(gender, [g,e,n,d,e,r]).
word(gene, [g,e,n,e]).
word(general, [g,e,n,e,r,a,l]).
word(generally, [g,e,n,e,r,a,l,l,y]).
word(generate, [g,e,n,e,r,a,t,e]).
word(generation, [g,e,n,e,r,a,t,i,o,n]).
word(genetic, [g,e,n,e,t,i,c]).
word(gentleman, [g,e,n,t,l,e,m,a,n]).
word(gently, [g,e,n,t,l,y]).
word(german, [g,e,r,m,a,n]).
word(gesture, [g,e,s,t,u,r,e]).
word(get, [g,e,t]).
word(ghost, [g,h,o,s,t]).
word(giant, [g,i,a,n,t]).
word(gift, [g,i,f,t]).
word(gifted, [g,i,f,t,e,d]).
word(girl, [g,i,r,l]).
word(girlfriend, [g,i,r,l,f,r,i,e,n,d]).
word(give, [g,i,v,e]).
word(given, [g,i,v,e,n]).
word(glad, [g,l,a,d]).
word(glance, [g,l,a,n,c,e]).
word(glass, [g,l,a,s,s]).
word(global, [g,l,o,b,a,l]).
word(glove, [g,l,o,v,e]).
word(go, [g,o]).
word(goal, [g,o,a,l]).
word(god, [g,o,d]).
word(gold, [g,o,l,d]).
word(golden, [g,o,l,d,e,n]).
word(golf, [g,o,l,f]).
word(good, [g,o,o,d]).
word(government, [g,o,v,e,r,n,m,e,n,t]).
word(governor, [g,o,v,e,r,n,o,r]).
word(grab, [g,r,a,b]).
word(grade, [g,r,a,d,e]).
word(gradually, [g,r,a,d,u,a,l,l,y]).
word(graduate, [g,r,a,d,u,a,t,e]).
word(grain, [g,r,a,i,n]).
word(grand, [g,r,a,n,d]).
word(grandfather, [g,r,a,n,d,f,a,t,h,e,r]).
word(grandmother, [g,r,a,n,d,m,o,t,h,e,r]).
word(grant, [g,r,a,n,t]).
word(grass, [g,r,a,s,s]).
word(grave, [g,r,a,v,e]).
word(gray, [g,r,a,y]).
word(great, [g,r,e,a,t]).
word(greatest, [g,r,e,a,t,e,s,t]).
word(green, [g,r,e,e,n]).
word(grocery, [g,r,o,c,e,r,y]).
word(ground, [g,r,o,u,n,d]).
word(group, [g,r,o,u,p]).
word(grow, [g,r,o,w]).
word(growing, [g,r,o,w,i,n,g]).
word(growth, [g,r,o,w,t,h]).
word(guarantee, [g,u,a,r,a,n,t,e,e]).
word(guard, [g,u,a,r,d]).
word(guess, [g,u,e,s,s]).
word(guest, [g,u,e,s,t]).
word(guide, [g,u,i,d,e]).
word(guideline, [g,u,i,d,e,l,i,n,e]).
word(guilty, [g,u,i,l,t,y]).
word(gun, [g,u,n]).
word(guy, [g,u,y]).
word(habit, [h,a,b,i,t]).
word(habitat, [h,a,b,i,t,a,t]).
word(hair, [h,a,i,r]).
word(half, [h,a,l,f]).
word(hall, [h,a,l,l]).
word(hand, [h,a,n,d]).
word(handful, [h,a,n,d,f,u,l]).
word(handle, [h,a,n,d,l,e]).
word(hang, [h,a,n,g]).
word(happen, [h,a,p,p,e,n]).
word(happy, [h,a,p,p,y]).
word(hard, [h,a,r,d]).
word(hardly, [h,a,r,d,l,y]).
word(hat, [h,a,t]).
word(hate, [h,a,t,e]).
word(have, [h,a,v,e]).
word(he, [h,e]).
word(head, [h,e,a,d]).
word(headline, [h,e,a,d,l,i,n,e]).
word(headquarters, [h,e,a,d,q,u,a,r,t,e,r,s]).
word(health, [h,e,a,l,t,h]).
word(healthy, [h,e,a,l,t,h,y]).
word(hear, [h,e,a,r]).
word(hearing, [h,e,a,r,i,n,g]).
word(heart, [h,e,a,r,t]).
word(heat, [h,e,a,t]).
word(heaven, [h,e,a,v,e,n]).
word(heavily, [h,e,a,v,i,l,y]).
word(heavy, [h,e,a,v,y]).
word(heel, [h,e,e,l]).
word(height, [h,e,i,g,h,t]).
word(helicopter, [h,e,l,i,c,o,p,t,e,r]).
word(hell, [h,e,l,l]).
word(hello, [h,e,l,l,o]).
word(help, [h,e,l,p]).
word(helpful, [h,e,l,p,f,u,l]).
word(her, [h,e,r]).
word(here, [h,e,r,e]).
word(heritage, [h,e,r,i,t,a,g,e]).
word(hero, [h,e,r,o]).
word(herself, [h,e,r,s,e,l,f]).
word(hey, [h,e,y]).
word(hi, [h,i]).
word(hide, [h,i,d,e]).
word(high, [h,i,g,h]).
word(highlight, [h,i,g,h,l,i,g,h,t]).
word(highly, [h,i,g,h,l,y]).
word(highway, [h,i,g,h,w,a,y]).
word(hill, [h,i,l,l]).
word(him, [h,i,m]).
word(himself, [h,i,m,s,e,l,f]).
word(hip, [h,i,p]).
word(hire, [h,i,r,e]).
word(his, [h,i,s]).
word(historian, [h,i,s,t,o,r,i,a,n]).
word(historic, [h,i,s,t,o,r,i,c]).
word(historical, [h,i,s,t,o,r,i,c,a,l]).
word(history, [h,i,s,t,o,r,y]).
word(hit, [h,i,t]).
word(hold, [h,o,l,d]).
word(hole, [h,o,l,e]).
word(holiday, [h,o,l,i,d,a,y]).
word(holy, [h,o,l,y]).
word(home, [h,o,m,e]).
word(homeless, [h,o,m,e,l,e,s,s]).
word(honest, [h,o,n,e,s,t]).
word(honey, [h,o,n,e,y]).
word(honor, [h,o,n,o,r]).
word(hope, [h,o,p,e]).
word(horizon, [h,o,r,i,z,o,n]).
word(horror, [h,o,r,r,o,r]).
word(horse, [h,o,r,s,e]).
word(hospital, [h,o,s,p,i,t,a,l]).
word(host, [h,o,s,t]).
word(hot, [h,o,t]).
word(hotel, [h,o,t,e,l]).
word(hour, [h,o,u,r]).
word(house, [h,o,u,s,e]).
word(household, [h,o,u,s,e,h,o,l,d]).
word(housing, [h,o,u,s,i,n,g]).
word(how, [h,o,w]).
word(however, [h,o,w,e,v,e,r]).
word(huge, [h,u,g,e]).
word(human, [h,u,m,a,n]).
word(humor, [h,u,m,o,r]).
word(hundred, [h,u,n,d,r,e,d]).
word(hungry, [h,u,n,g,r,y]).
word(hunter, [h,u,n,t,e,r]).
word(hunting, [h,u,n,t,i,n,g]).
word(hurt, [h,u,r,t]).
word(husband, [h,u,s,b,a,n,d]).
word(hypothesis, [h,y,p,o,t,h,e,s,i,s]).
word(i, [i]).
word(ice, [i,c,e]).
word(idea, [i,d,e,a]).
word(ideal, [i,d,e,a,l]).
word(identification, [i,d,e,n,t,i,f,i,c,a,t,i,o,n]).
word(identify, [i,d,e,n,t,i,f,y]).
word(identity, [i,d,e,n,t,i,t,y]).
word(ie, [i,e]).
word(if, [i,f]).
word(ignore, [i,g,n,o,r,e]).
word(ill, [i,l,l]).
word(illegal, [i,l,l,e,g,a,l]).
word(illness, [i,l,l,n,e,s,s]).
word(illustrate, [i,l,l,u,s,t,r,a,t,e]).
word(image, [i,m,a,g,e]).
word(imagination, [i,m,a,g,i,n,a,t,i,o,n]).
word(imagine, [i,m,a,g,i,n,e]).
word(immediate, [i,m,m,e,d,i,a,t,e]).
word(immediately, [i,m,m,e,d,i,a,t,e,l,y]).
word(immigrant, [i,m,m,i,g,r,a,n,t]).
word(immigration, [i,m,m,i,g,r,a,t,i,o,n]).
word(impact, [i,m,p,a,c,t]).
word(implement, [i,m,p,l,e,m,e,n,t]).
word(implication, [i,m,p,l,i,c,a,t,i,o,n]).
word(imply, [i,m,p,l,y]).
word(importance, [i,m,p,o,r,t,a,n,c,e]).
word(important, [i,m,p,o,r,t,a,n,t]).
word(impose, [i,m,p,o,s,e]).
word(impossible, [i,m,p,o,s,s,i,b,l,e]).
word(impress, [i,m,p,r,e,s,s]).
word(impression, [i,m,p,r,e,s,s,i,o,n]).
word(impressive, [i,m,p,r,e,s,s,i,v,e]).
word(improve, [i,m,p,r,o,v,e]).
word(improvement, [i,m,p,r,o,v,e,m,e,n,t]).
word(in, [i,n]).
word(incentive, [i,n,c,e,n,t,i,v,e]).
word(incident, [i,n,c,i,d,e,n,t]).
word(include, [i,n,c,l,u,d,e]).
word(including, [i,n,c,l,u,d,i,n,g]).
word(income, [i,n,c,o,m,e]).
word(incorporate, [i,n,c,o,r,p,o,r,a,t,e]).
word(increase, [i,n,c,r,e,a,s,e]).
word(increased, [i,n,c,r,e,a,s,e,d]).
word(increasing, [i,n,c,r,e,a,s,i,n,g]).
word(increasingly, [i,n,c,r,e,a,s,i,n,g,l,y]).
word(incredible, [i,n,c,r,e,d,i,b,l,e]).
word(indeed, [i,n,d,e,e,d]).
word(independence, [i,n,d,e,p,e,n,d,e,n,c,e]).
word(independent, [i,n,d,e,p,e,n,d,e,n,t]).
word(index, [i,n,d,e,x]).
word(indian, [i,n,d,i,a,n]).
word(indicate, [i,n,d,i,c,a,t,e]).
word(indication, [i,n,d,i,c,a,t,i,o,n]).
word(individual, [i,n,d,i,v,i,d,u,a,l]).
word(industrial, [i,n,d,u,s,t,r,i,a,l]).
word(industry, [i,n,d,u,s,t,r,y]).
word(infant, [i,n,f,a,n,t]).
word(infection, [i,n,f,e,c,t,i,o,n]).
word(inflation, [i,n,f,l,a,t,i,o,n]).
word(influence, [i,n,f,l,u,e,n,c,e]).
word(inform, [i,n,f,o,r,m]).
word(information, [i,n,f,o,r,m,a,t,i,o,n]).
word(ingredient, [i,n,g,r,e,d,i,e,n,t]).
word(initial, [i,n,i,t,i,a,l]).
word(initially, [i,n,i,t,i,a,l,l,y]).
word(initiative, [i,n,i,t,i,a,t,i,v,e]).
word(injury, [i,n,j,u,r,y]).
word(inner, [i,n,n,e,r]).
word(innocent, [i,n,n,o,c,e,n,t]).
word(inquiry, [i,n,q,u,i,r,y]).
word(inside, [i,n,s,i,d,e]).
word(insight, [i,n,s,i,g,h,t]).
word(insist, [i,n,s,i,s,t]).
word(inspire, [i,n,s,p,i,r,e]).
word(install, [i,n,s,t,a,l,l]).
word(instance, [i,n,s,t,a,n,c,e]).
word(instead, [i,n,s,t,e,a,d]).
word(institution, [i,n,s,t,i,t,u,t,i,o,n]).
word(institutional, [i,n,s,t,i,t,u,t,i,o,n,a,l]).
word(instruction, [i,n,s,t,r,u,c,t,i,o,n]).
word(instructor, [i,n,s,t,r,u,c,t,o,r]).
word(instrument, [i,n,s,t,r,u,m,e,n,t]).
word(insurance, [i,n,s,u,r,a,n,c,e]).
word(intellectual, [i,n,t,e,l,l,e,c,t,u,a,l]).
word(intelligence, [i,n,t,e,l,l,i,g,e,n,c,e]).
word(intend, [i,n,t,e,n,d]).
word(intense, [i,n,t,e,n,s,e]).
word(intensity, [i,n,t,e,n,s,i,t,y]).
word(intention, [i,n,t,e,n,t,i,o,n]).
word(interaction, [i,n,t,e,r,a,c,t,i,o,n]).
word(interest, [i,n,t,e,r,e,s,t]).
word(interested, [i,n,t,e,r,e,s,t,e,d]).
word(interesting, [i,n,t,e,r,e,s,t,i,n,g]).
word(internal, [i,n,t,e,r,n,a,l]).
word(international, [i,n,t,e,r,n,a,t,i,o,n,a,l]).
word(internet, [i,n,t,e,r,n,e,t]).
word(interpret, [i,n,t,e,r,p,r,e,t]).
word(interpretation, [i,n,t,e,r,p,r,e,t,a,t,i,o,n]).
word(intervention, [i,n,t,e,r,v,e,n,t,i,o,n]).
word(interview, [i,n,t,e,r,v,i,e,w]).
word(into, [i,n,t,o]).
word(introduce, [i,n,t,r,o,d,u,c,e]).
word(introduction, [i,n,t,r,o,d,u,c,t,i,o,n]).
word(invasion, [i,n,v,a,s,i,o,n]).
word(invest, [i,n,v,e,s,t]).
word(investigate, [i,n,v,e,s,t,i,g,a,t,e]).
word(investigation, [i,n,v,e,s,t,i,g,a,t,i,o,n]).
word(investigator, [i,n,v,e,s,t,i,g,a,t,o,r]).
word(investment, [i,n,v,e,s,t,m,e,n,t]).
word(investor, [i,n,v,e,s,t,o,r]).
word(invite, [i,n,v,i,t,e]).
word(involve, [i,n,v,o,l,v,e]).
word(involved, [i,n,v,o,l,v,e,d]).
word(involvement, [i,n,v,o,l,v,e,m,e,n,t]).
word(iraqi, [i,r,a,q,i]).
word(irish, [i,r,i,s,h]).
word(iron, [i,r,o,n]).
word(islamic, [i,s,l,a,m,i,c]).
word(island, [i,s,l,a,n,d]).
word(israeli, [i,s,r,a,e,l,i]).
word(issue, [i,s,s,u,e]).
word(it, [i,t]).
word(italian, [i,t,a,l,i,a,n]).
word(item, [i,t,e,m]).
word(its, [i,t,s]).
word(itself, [i,t,s,e,l,f]).
word(jacket, [j,a,c,k,e,t]).
word(jail, [j,a,i,l]).
word(japanese, [j,a,p,a,n,e,s,e]).
word(jet, [j,e,t]).
word(jew, [j,e,w]).
word(jewish, [j,e,w,i,s,h]).
word(job, [j,o,b]).
word(join, [j,o,i,n]).
word(joint, [j,o,i,n,t]).
word(joke, [j,o,k,e]).
word(journal, [j,o,u,r,n,a,l]).
word(journalist, [j,o,u,r,n,a,l,i,s,t]).
word(journey, [j,o,u,r,n,e,y]).
word(joy, [j,o,y]).
word(judge, [j,u,d,g,e]).
word(judgment, [j,u,d,g,m,e,n,t]).
word(juice, [j,u,i,c,e]).
word(jump, [j,u,m,p]).
word(junior, [j,u,n,i,o,r]).
word(jury, [j,u,r,y]).
word(just, [j,u,s,t]).
word(justice, [j,u,s,t,i,c,e]).
word(justify, [j,u,s,t,i,f,y]).
word(keep, [k,e,e,p]).
word(key, [k,e,y]).
word(kick, [k,i,c,k]).
word(kid, [k,i,d]).
word(kill, [k,i,l,l]).
word(killer, [k,i,l,l,e,r]).
word(killing, [k,i,l,l,i,n,g]).
word(kind, [k,i,n,d]).
word(king, [k,i,n,g]).
word(kiss, [k,i,s,s]).
word(kitchen, [k,i,t,c,h,e,n]).
word(knee, [k,n,e,e]).
word(knife, [k,n,i,f,e]).
word(knock, [k,n,o,c,k]).
word(know, [k,n,o,w]).
word(knowledge, [k,n,o,w,l,e,d,g,e]).
word(lab, [l,a,b]).
word(label, [l,a,b,e,l]).
word(labor, [l,a,b,o,r]).
word(laboratory, [l,a,b,o,r,a,t,o,r,y]).
word(lack, [l,a,c,k]).
word(lady, [l,a,d,y]).
word(lake, [l,a,k,e]).
word(land, [l,a,n,d]).
word(landscape, [l,a,n,d,s,c,a,p,e]).
word(language, [l,a,n,g,u,a,g,e]).
word(lap, [l,a,p]).
word(large, [l,a,r,g,e]).
word(largely, [l,a,r,g,e,l,y]).
word(last, [l,a,s,t]).
word(late, [l,a,t,e]).
word(later, [l,a,t,e,r]).
word(latin, [l,a,t,i,n]).
word(latter, [l,a,t,t,e,r]).
word(laugh, [l,a,u,g,h]).
word(launch, [l,a,u,n,c,h]).
word(law, [l,a,w]).
word(lawn, [l,a,w,n]).
word(lawsuit, [l,a,w,s,u,i,t]).
word(lawyer, [l,a,w,y,e,r]).
word(lay, [l,a,y]).
word(layer, [l,a,y,e,r]).
word(lead, [l,e,a,d]).
word(leader, [l,e,a,d,e,r]).
word(leadership, [l,e,a,d,e,r,s,h,i,p]).
word(leading, [l,e,a,d,i,n,g]).
word(leaf, [l,e,a,f]).
word(league, [l,e,a,g,u,e]).
word(lean, [l,e,a,n]).
word(learn, [l,e,a,r,n]).
word(learning, [l,e,a,r,n,i,n,g]).
word(least, [l,e,a,s,t]).
word(leather, [l,e,a,t,h,e,r]).
word(leave, [l,e,a,v,e]).
word(left, [l,e,f,t]).
word(leg, [l,e,g]).
word(legacy, [l,e,g,a,c,y]).
word(legal, [l,e,g,a,l]).
word(legend, [l,e,g,e,n,d]).
word(legislation, [l,e,g,i,s,l,a,t,i,o,n]).
word(legitimate, [l,e,g,i,t,i,m,a,t,e]).
word(lemon, [l,e,m,o,n]).
word(length, [l,e,n,g,t,h]).
word(less, [l,e,s,s]).
word(lesson, [l,e,s,s,o,n]).
word(let, [l,e,t]).
word(letter, [l,e,t,t,e,r]).
word(level, [l,e,v,e,l]).
word(liberal, [l,i,b,e,r,a,l]).
word(library, [l,i,b,r,a,r,y]).
word(license, [l,i,c,e,n,s,e]).
word(lie, [l,i,e]).
word(life, [l,i,f,e]).
word(lifestyle, [l,i,f,e,s,t,y,l,e]).
word(lifetime, [l,i,f,e,t,i,m,e]).
word(lift, [l,i,f,t]).
word(light, [l,i,g,h,t]).
word(like, [l,i,k,e]).
word(likely, [l,i,k,e,l,y]).
word(limit, [l,i,m,i,t]).
word(limitation, [l,i,m,i,t,a,t,i,o,n]).
word(limited, [l,i,m,i,t,e,d]).
word(line, [l,i,n,e]).
word(link, [l,i,n,k]).
word(lip, [l,i,p]).
word(list, [l,i,s,t]).
word(listen, [l,i,s,t,e,n]).
word(literally, [l,i,t,e,r,a,l,l,y]).
word(literary, [l,i,t,e,r,a,r,y]).
word(literature, [l,i,t,e,r,a,t,u,r,e]).
word(little, [l,i,t,t,l,e]).
word(live, [l,i,v,e]).
word(living, [l,i,v,i,n,g]).
word(load, [l,o,a,d]).
word(loan, [l,o,a,n]).
word(local, [l,o,c,a,l]).
word(locate, [l,o,c,a,t,e]).
word(location, [l,o,c,a,t,i,o,n]).
word(lock, [l,o,c,k]).
word(long, [l,o,n,g]).
word(look, [l,o,o,k]).
word(loose, [l,o,o,s,e]).
word(lose, [l,o,s,e]).
word(loss, [l,o,s,s]).
word(lost, [l,o,s,t]).
word(lot, [l,o,t]).
word(lots, [l,o,t,s]).
word(loud, [l,o,u,d]).
word(love, [l,o,v,e]).
word(lovely, [l,o,v,e,l,y]).
word(lover, [l,o,v,e,r]).
word(low, [l,o,w]).
word(lower, [l,o,w,e,r]).
word(luck, [l,u,c,k]).
word(lucky, [l,u,c,k,y]).
word(lunch, [l,u,n,c,h]).
word(lung, [l,u,n,g]).
word(machine, [m,a,c,h,i,n,e]).
word(mad, [m,a,d]).
word(magazine, [m,a,g,a,z,i,n,e]).
word(mail, [m,a,i,l]).
word(main, [m,a,i,n]).
word(mainly, [m,a,i,n,l,y]).
word(maintain, [m,a,i,n,t,a,i,n]).
word(maintenance, [m,a,i,n,t,e,n,a,n,c,e]).
word(major, [m,a,j,o,r]).
word(majority, [m,a,j,o,r,i,t,y]).
word(make, [m,a,k,e]).
word(maker, [m,a,k,e,r]).
word(makeup, [m,a,k,e,u,p]).
word(male, [m,a,l,e]).
word(mall, [m,a,l,l]).
word(man, [m,a,n]).
word(manage, [m,a,n,a,g,e]).
word(management, [m,a,n,a,g,e,m,e,n,t]).
word(manager, [m,a,n,a,g,e,r]).
word(manner, [m,a,n,n,e,r]).
word(manufacturer, [m,a,n,u,f,a,c,t,u,r,e,r]).
word(manufacturing, [m,a,n,u,f,a,c,t,u,r,i,n,g]).
word(many, [m,a,n,y]).
word(map, [m,a,p]).
word(margin, [m,a,r,g,i,n]).
word(mark, [m,a,r,k]).
word(market, [m,a,r,k,e,t]).
word(marketing, [m,a,r,k,e,t,i,n,g]).
word(marriage, [m,a,r,r,i,a,g,e]).
word(married, [m,a,r,r,i,e,d]).
word(marry, [m,a,r,r,y]).
word(mask, [m,a,s,k]).
word(mass, [m,a,s,s]).
word(massive, [m,a,s,s,i,v,e]).
word(master, [m,a,s,t,e,r]).
word(match, [m,a,t,c,h]).
word(material, [m,a,t,e,r,i,a,l]).
word(math, [m,a,t,h]).
word(matter, [m,a,t,t,e,r]).
word(may, [m,a,y]).
word(maybe, [m,a,y,b,e]).
word(mayor, [m,a,y,o,r]).
word(me, [m,e]).
word(meal, [m,e,a,l]).
word(mean, [m,e,a,n]).
word(meaning, [m,e,a,n,i,n,g]).
word(meanwhile, [m,e,a,n,w,h,i,l,e]).
word(measure, [m,e,a,s,u,r,e]).
word(measurement, [m,e,a,s,u,r,e,m,e,n,t]).
word(meat, [m,e,a,t]).
word(mechanism, [m,e,c,h,a,n,i,s,m]).
word(media, [m,e,d,i,a]).
word(medical, [m,e,d,i,c,a,l]).
word(medication, [m,e,d,i,c,a,t,i,o,n]).
word(medicine, [m,e,d,i,c,i,n,e]).
word(medium, [m,e,d,i,u,m]).
word(meet, [m,e,e,t]).
word(meeting, [m,e,e,t,i,n,g]).
word(member, [m,e,m,b,e,r]).
word(membership, [m,e,m,b,e,r,s,h,i,p]).
word(memory, [m,e,m,o,r,y]).
word(mental, [m,e,n,t,a,l]).
word(mention, [m,e,n,t,i,o,n]).
word(menu, [m,e,n,u]).
word(mere, [m,e,r,e]).
word(merely, [m,e,r,e,l,y]).
word(mess, [m,e,s,s]).
word(message, [m,e,s,s,a,g,e]).
word(metal, [m,e,t,a,l]).
word(meter, [m,e,t,e,r]).
word(method, [m,e,t,h,o,d]).
word(mexican, [m,e,x,i,c,a,n]).
word(middle, [m,i,d,d,l,e]).
word(might, [m,i,g,h,t]).
word(military, [m,i,l,i,t,a,r,y]).
word(milk, [m,i,l,k]).
word(million, [m,i,l,l,i,o,n]).
word(mind, [m,i,n,d]).
word(mine, [m,i,n,e]).
word(minister, [m,i,n,i,s,t,e,r]).
word(minor, [m,i,n,o,r]).
word(minority, [m,i,n,o,r,i,t,y]).
word(minute, [m,i,n,u,t,e]).
word(miracle, [m,i,r,a,c,l,e]).
word(mirror, [m,i,r,r,o,r]).
word(miss, [m,i,s,s]).
word(missile, [m,i,s,s,i,l,e]).
word(mission, [m,i,s,s,i,o,n]).
word(mistake, [m,i,s,t,a,k,e]).
word(mix, [m,i,x]).
word(mixture, [m,i,x,t,u,r,e]).
word(mode, [m,o,d,e]).
word(model, [m,o,d,e,l]).
word(moderate, [m,o,d,e,r,a,t,e]).
word(modern, [m,o,d,e,r,n]).
word(modest, [m,o,d,e,s,t]).
word(mom, [m,o,m]).
word(moment, [m,o,m,e,n,t]).
word(money, [m,o,n,e,y]).
word(monitor, [m,o,n,i,t,o,r]).
word(month, [m,o,n,t,h]).
word(mood, [m,o,o,d]).
word(moon, [m,o,o,n]).
word(moral, [m,o,r,a,l]).
word(more, [m,o,r,e]).
word(moreover, [m,o,r,e,o,v,e,r]).
word(morning, [m,o,r,n,i,n,g]).
word(mortgage, [m,o,r,t,g,a,g,e]).
word(most, [m,o,s,t]).
word(mostly, [m,o,s,t,l,y]).
word(mother, [m,o,t,h,e,r]).
word(motion, [m,o,t,i,o,n]).
word(motivation, [m,o,t,i,v,a,t,i,o,n]).
word(motor, [m,o,t,o,r]).
word(mount, [m,o,u,n,t]).
word(mountain, [m,o,u,n,t,a,i,n]).
word(mouse, [m,o,u,s,e]).
word(mouth, [m,o,u,t,h]).
word(move, [m,o,v,e]).
word(movement, [m,o,v,e,m,e,n,t]).
word(movie, [m,o,v,i,e]).
word(mr, [m,r]).
word(mrs, [m,r,s]).
word(ms, [m,s]).
word(much, [m,u,c,h]).
word(multiple, [m,u,l,t,i,p,l,e]).
word(murder, [m,u,r,d,e,r]).
word(muscle, [m,u,s,c,l,e]).
word(museum, [m,u,s,e,u,m]).
word(music, [m,u,s,i,c]).
word(musical, [m,u,s,i,c,a,l]).
word(musician, [m,u,s,i,c,i,a,n]).
word(muslim, [m,u,s,l,i,m]).
word(must, [m,u,s,t]).
word(mutual, [m,u,t,u,a,l]).
word(my, [m,y]).
word(myself, [m,y,s,e,l,f]).
word(mystery, [m,y,s,t,e,r,y]).
word(myth, [m,y,t,h]).
word(naked, [n,a,k,e,d]).
word(name, [n,a,m,e]).
word(narrative, [n,a,r,r,a,t,i,v,e]).
word(narrow, [n,a,r,r,o,w]).
word(nation, [n,a,t,i,o,n]).
word(national, [n,a,t,i,o,n,a,l]).
word(native, [n,a,t,i,v,e]).
word(natural, [n,a,t,u,r,a,l]).
word(naturally, [n,a,t,u,r,a,l,l,y]).
word(nature, [n,a,t,u,r,e]).
word(near, [n,e,a,r]).
word(nearby, [n,e,a,r,b,y]).
word(nearly, [n,e,a,r,l,y]).
word(necessarily, [n,e,c,e,s,s,a,r,i,l,y]).
word(necessary, [n,e,c,e,s,s,a,r,y]).
word(neck, [n,e,c,k]).
word(need, [n,e,e,d]).
word(negative, [n,e,g,a,t,i,v,e]).
word(negotiate, [n,e,g,o,t,i,a,t,e]).
word(negotiation, [n,e,g,o,t,i,a,t,i,o,n]).
word(neighbor, [n,e,i,g,h,b,o,r]).
word(neighborhood, [n,e,i,g,h,b,o,r,h,o,o,d]).
word(neither, [n,e,i,t,h,e,r]).
word(nerve, [n,e,r,v,e]).
word(nervous, [n,e,r,v,o,u,s]).
word(net, [n,e,t]).
word(network, [n,e,t,w,o,r,k]).
word(never, [n,e,v,e,r]).
word(nevertheless, [n,e,v,e,r,t,h,e,l,e,s,s]).
word(new, [n,e,w]).
word(newly, [n,e,w,l,y]).
word(news, [n,e,w,s]).
word(newspaper, [n,e,w,s,p,a,p,e,r]).
word(next, [n,e,x,t]).
word(nice, [n,i,c,e]).
word(night, [n,i,g,h,t]).
word(nine, [n,i,n,e]).
word(no, [n,o]).
word(nobody, [n,o,b,o,d,y]).
word(nod, [n,o,d]).
word(noise, [n,o,i,s,e]).
word(nomination, [n,o,m,i,n,a,t,i,o,n]).
word(none, [n,o,n,e]).
word(nonetheless, [n,o,n,e,t,h,e,l,e,s,s]).
word(nor, [n,o,r]).
word(normal, [n,o,r,m,a,l]).
word(normally, [n,o,r,m,a,l,l,y]).
word(north, [n,o,r,t,h]).
word(northern, [n,o,r,t,h,e,r,n]).
word(nose, [n,o,s,e]).
word(not, [n,o,t]).
word(note, [n,o,t,e]).
word(nothing, [n,o,t,h,i,n,g]).
word(notice, [n,o,t,i,c,e]).
word(notion, [n,o,t,i,o,n]).
word(novel, [n,o,v,e,l]).
word(now, [n,o,w]).
word(nowhere, [n,o,w,h,e,r,e]).
word(nuclear, [n,u,c,l,e,a,r]).
word(number, [n,u,m,b,e,r]).
word(numerous, [n,u,m,e,r,o,u,s]).
word(nurse, [n,u,r,s,e]).
word(nut, [n,u,t]).
word(object, [o,b,j,e,c,t]).
word(objective, [o,b,j,e,c,t,i,v,e]).
word(obligation, [o,b,l,i,g,a,t,i,o,n]).
word(observation, [o,b,s,e,r,v,a,t,i,o,n]).
word(observe, [o,b,s,e,r,v,e]).
word(observer, [o,b,s,e,r,v,e,r]).
word(obtain, [o,b,t,a,i,n]).
word(obvious, [o,b,v,i,o,u,s]).
word(obviously, [o,b,v,i,o,u,s,l,y]).
word(occasion, [o,c,c,a,s,i,o,n]).
word(occasionally, [o,c,c,a,s,i,o,n,a,l,l,y]).
word(occupation, [o,c,c,u,p,a,t,i,o,n]).
word(occupy, [o,c,c,u,p,y]).
word(occur, [o,c,c,u,r]).
word(ocean, [o,c,e,a,n]).
word(odd, [o,d,d]).
word(odds, [o,d,d,s]).
word(of, [o,f]).
word(off, [o,f,f]).
word(offense, [o,f,f,e,n,s,e]).
word(offensive, [o,f,f,e,n,s,i,v,e]).
word(offer, [o,f,f,e,r]).
word(office, [o,f,f,i,c,e]).
word(officer, [o,f,f,i,c,e,r]).
word(official, [o,f,f,i,c,i,a,l]).
word(often, [o,f,t,e,n]).
word(oh, [o,h]).
word(oil, [o,i,l]).
word(ok, [o,k]).
word(okay, [o,k,a,y]).
word(old, [o,l,d]).
word(olympic, [o,l,y,m,p,i,c]).
word(on, [o,n]).
word(once, [o,n,c,e]).
word(one, [o,n,e]).
word(ongoing, [o,n,g,o,i,n,g]).
word(onion, [o,n,i,o,n]).
word(online, [o,n,l,i,n,e]).
word(only, [o,n,l,y]).
word(onto, [o,n,t,o]).
word(open, [o,p,e,n]).
word(opening, [o,p,e,n,i,n,g]).
word(operate, [o,p,e,r,a,t,e]).
word(operating, [o,p,e,r,a,t,i,n,g]).
word(operation, [o,p,e,r,a,t,i,o,n]).
word(operator, [o,p,e,r,a,t,o,r]).
word(opinion, [o,p,i,n,i,o,n]).
word(opponent, [o,p,p,o,n,e,n,t]).
word(opportunity, [o,p,p,o,r,t,u,n,i,t,y]).
word(oppose, [o,p,p,o,s,e]).
word(opposite, [o,p,p,o,s,i,t,e]).
word(opposition, [o,p,p,o,s,i,t,i,o,n]).
word(option, [o,p,t,i,o,n]).
word(or, [o,r]).
word(orange, [o,r,a,n,g,e]).
word(order, [o,r,d,e,r]).
word(ordinary, [o,r,d,i,n,a,r,y]).
word(organic, [o,r,g,a,n,i,c]).
word(organization, [o,r,g,a,n,i,z,a,t,i,o,n]).
word(organize, [o,r,g,a,n,i,z,e]).
word(orientation, [o,r,i,e,n,t,a,t,i,o,n]).
word(origin, [o,r,i,g,i,n]).
word(original, [o,r,i,g,i,n,a,l]).
word(originally, [o,r,i,g,i,n,a,l,l,y]).
word(other, [o,t,h,e,r]).
word(others, [o,t,h,e,r,s]).
word(otherwise, [o,t,h,e,r,w,i,s,e]).
word(ought, [o,u,g,h,t]).
word(our, [o,u,r]).
word(ourselves, [o,u,r,s,e,l,v,e,s]).
word(out, [o,u,t]).
word(outcome, [o,u,t,c,o,m,e]).
word(outside, [o,u,t,s,i,d,e]).
word(oven, [o,v,e,n]).
word(over, [o,v,e,r]).
word(overall, [o,v,e,r,a,l,l]).
word(overcome, [o,v,e,r,c,o,m,e]).
word(overlook, [o,v,e,r,l,o,o,k]).
word(owe, [o,w,e]).
word(own, [o,w,n]).
word(owner, [o,w,n,e,r]).
word(pace, [p,a,c,e]).
word(pack, [p,a,c,k]).
word(package, [p,a,c,k,a,g,e]).
word(page, [p,a,g,e]).
word(pain, [p,a,i,n]).
word(painful, [p,a,i,n,f,u,l]).
word(paint, [p,a,i,n,t]).
word(painter, [p,a,i,n,t,e,r]).
word(painting, [p,a,i,n,t,i,n,g]).
word(pair, [p,a,i,r]).
word(pale, [p,a,l,e]).
word(palestinian, [p,a,l,e,s,t,i,n,i,a,n]).
word(palm, [p,a,l,m]).
word(pan, [p,a,n]).
word(panel, [p,a,n,e,l]).
word(pant, [p,a,n,t]).
word(paper, [p,a,p,e,r]).
word(parent, [p,a,r,e,n,t]).
word(park, [p,a,r,k]).
word(parking, [p,a,r,k,i,n,g]).
word(part, [p,a,r,t]).
word(participant, [p,a,r,t,i,c,i,p,a,n,t]).
word(participate, [p,a,r,t,i,c,i,p,a,t,e]).
word(participation, [p,a,r,t,i,c,i,p,a,t,i,o,n]).
word(particular, [p,a,r,t,i,c,u,l,a,r]).
word(particularly, [p,a,r,t,i,c,u,l,a,r,l,y]).
word(partly, [p,a,r,t,l,y]).
word(partner, [p,a,r,t,n,e,r]).
word(partnership, [p,a,r,t,n,e,r,s,h,i,p]).
word(party, [p,a,r,t,y]).
word(pass, [p,a,s,s]).
word(passage, [p,a,s,s,a,g,e]).
word(passenger, [p,a,s,s,e,n,g,e,r]).
word(passion, [p,a,s,s,i,o,n]).
word(past, [p,a,s,t]).
word(patch, [p,a,t,c,h]).
word(path, [p,a,t,h]).
word(patient, [p,a,t,i,e,n,t]).
word(pattern, [p,a,t,t,e,r,n]).
word(pause, [p,a,u,s,e]).
word(pay, [p,a,y]).
word(payment, [p,a,y,m,e,n,t]).
word(pc, [p,c]).
word(peace, [p,e,a,c,e]).
word(peak, [p,e,a,k]).
word(peer, [p,e,e,r]).
word(penalty, [p,e,n,a,l,t,y]).
word(people, [p,e,o,p,l,e]).
word(pepper, [p,e,p,p,e,r]).
word(per, [p,e,r]).
word(perceive, [p,e,r,c,e,i,v,e]).
word(percentage, [p,e,r,c,e,n,t,a,g,e]).
word(perception, [p,e,r,c,e,p,t,i,o,n]).
word(perfect, [p,e,r,f,e,c,t]).
word(perfectly, [p,e,r,f,e,c,t,l,y]).
word(perform, [p,e,r,f,o,r,m]).
word(performance, [p,e,r,f,o,r,m,a,n,c,e]).
word(perhaps, [p,e,r,h,a,p,s]).
word(period, [p,e,r,i,o,d]).
word(permanent, [p,e,r,m,a,n,e,n,t]).
word(permission, [p,e,r,m,i,s,s,i,o,n]).
word(permit, [p,e,r,m,i,t]).
word(person, [p,e,r,s,o,n]).
word(personal, [p,e,r,s,o,n,a,l]).
word(personality, [p,e,r,s,o,n,a,l,i,t,y]).
word(personally, [p,e,r,s,o,n,a,l,l,y]).
word(personnel, [p,e,r,s,o,n,n,e,l]).
word(perspective, [p,e,r,s,p,e,c,t,i,v,e]).
word(persuade, [p,e,r,s,u,a,d,e]).
word(pet, [p,e,t]).
word(phase, [p,h,a,s,e]).
word(phenomenon, [p,h,e,n,o,m,e,n,o,n]).
word(philosophy, [p,h,i,l,o,s,o,p,h,y]).
word(phone, [p,h,o,n,e]).
word(photo, [p,h,o,t,o]).
word(photograph, [p,h,o,t,o,g,r,a,p,h]).
word(photographer, [p,h,o,t,o,g,r,a,p,h,e,r]).
word(phrase, [p,h,r,a,s,e]).
word(physical, [p,h,y,s,i,c,a,l]).
word(physically, [p,h,y,s,i,c,a,l,l,y]).
word(physician, [p,h,y,s,i,c,i,a,n]).
word(piano, [p,i,a,n,o]).
word(pick, [p,i,c,k]).
word(picture, [p,i,c,t,u,r,e]).
word(pie, [p,i,e]).
word(piece, [p,i,e,c,e]).
word(pile, [p,i,l,e]).
word(pilot, [p,i,l,o,t]).
word(pine, [p,i,n,e]).
word(pink, [p,i,n,k]).
word(pipe, [p,i,p,e]).
word(pitch, [p,i,t,c,h]).
word(place, [p,l,a,c,e]).
word(plan, [p,l,a,n]).
word(plane, [p,l,a,n,e]).
word(planet, [p,l,a,n,e,t]).
word(planning, [p,l,a,n,n,i,n,g]).
word(plant, [p,l,a,n,t]).
word(plastic, [p,l,a,s,t,i,c]).
word(plate, [p,l,a,t,e]).
word(platform, [p,l,a,t,f,o,r,m]).
word(play, [p,l,a,y]).
word(player, [p,l,a,y,e,r]).
word(please, [p,l,e,a,s,e]).
word(pleasure, [p,l,e,a,s,u,r,e]).
word(plenty, [p,l,e,n,t,y]).
word(plot, [p,l,o,t]).
word(plus, [p,l,u,s]).
word(pm, [p,m]).
word(pocket, [p,o,c,k,e,t]).
word(poem, [p,o,e,m]).
word(poet, [p,o,e,t]).
word(poetry, [p,o,e,t,r,y]).
word(point, [p,o,i,n,t]).
word(pole, [p,o,l,e]).
word(police, [p,o,l,i,c,e]).
word(policy, [p,o,l,i,c,y]).
word(political, [p,o,l,i,t,i,c,a,l]).
word(politically, [p,o,l,i,t,i,c,a,l,l,y]).
word(politician, [p,o,l,i,t,i,c,i,a,n]).
word(politics, [p,o,l,i,t,i,c,s]).
word(poll, [p,o,l,l]).
word(pollution, [p,o,l,l,u,t,i,o,n]).
word(pool, [p,o,o,l]).
word(poor, [p,o,o,r]).
word(pop, [p,o,p]).
word(popular, [p,o,p,u,l,a,r]).
word(population, [p,o,p,u,l,a,t,i,o,n]).
word(porch, [p,o,r,c,h]).
word(port, [p,o,r,t]).
word(portion, [p,o,r,t,i,o,n]).
word(portrait, [p,o,r,t,r,a,i,t]).
word(portray, [p,o,r,t,r,a,y]).
word(pose, [p,o,s,e]).
word(position, [p,o,s,i,t,i,o,n]).
word(positive, [p,o,s,i,t,i,v,e]).
word(possess, [p,o,s,s,e,s,s]).
word(possibility, [p,o,s,s,i,b,i,l,i,t,y]).
word(possible, [p,o,s,s,i,b,l,e]).
word(possibly, [p,o,s,s,i,b,l,y]).
word(post, [p,o,s,t]).
word(pot, [p,o,t]).
word(potato, [p,o,t,a,t,o]).
word(potential, [p,o,t,e,n,t,i,a,l]).
word(potentially, [p,o,t,e,n,t,i,a,l,l,y]).
word(pound, [p,o,u,n,d]).
word(pour, [p,o,u,r]).
word(poverty, [p,o,v,e,r,t,y]).
word(powder, [p,o,w,d,e,r]).
word(power, [p,o,w,e,r]).
word(powerful, [p,o,w,e,r,f,u,l]).
word(practical, [p,r,a,c,t,i,c,a,l]).
word(practice, [p,r,a,c,t,i,c,e]).
word(pray, [p,r,a,y]).
word(prayer, [p,r,a,y,e,r]).
word(precisely, [p,r,e,c,i,s,e,l,y]).
word(predict, [p,r,e,d,i,c,t]).
word(prefer, [p,r,e,f,e,r]).
word(preference, [p,r,e,f,e,r,e,n,c,e]).
word(pregnancy, [p,r,e,g,n,a,n,c,y]).
word(pregnant, [p,r,e,g,n,a,n,t]).
word(preparation, [p,r,e,p,a,r,a,t,i,o,n]).
word(prepare, [p,r,e,p,a,r,e]).
word(prescription, [p,r,e,s,c,r,i,p,t,i,o,n]).
word(presence, [p,r,e,s,e,n,c,e]).
word(present, [p,r,e,s,e,n,t]).
word(presentation, [p,r,e,s,e,n,t,a,t,i,o,n]).
word(preserve, [p,r,e,s,e,r,v,e]).
word(president, [p,r,e,s,i,d,e,n,t]).
word(presidential, [p,r,e,s,i,d,e,n,t,i,a,l]).
word(press, [p,r,e,s,s]).
word(pressure, [p,r,e,s,s,u,r,e]).
word(pretend, [p,r,e,t,e,n,d]).
word(pretty, [p,r,e,t,t,y]).
word(prevent, [p,r,e,v,e,n,t]).
word(previous, [p,r,e,v,i,o,u,s]).
word(previously, [p,r,e,v,i,o,u,s,l,y]).
word(price, [p,r,i,c,e]).
word(pride, [p,r,i,d,e]).
word(priest, [p,r,i,e,s,t]).
word(primarily, [p,r,i,m,a,r,i,l,y]).
word(primary, [p,r,i,m,a,r,y]).
word(prime, [p,r,i,m,e]).
word(principal, [p,r,i,n,c,i,p,a,l]).
word(principle, [p,r,i,n,c,i,p,l,e]).
word(print, [p,r,i,n,t]).
word(prior, [p,r,i,o,r]).
word(priority, [p,r,i,o,r,i,t,y]).
word(prison, [p,r,i,s,o,n]).
word(prisoner, [p,r,i,s,o,n,e,r]).
word(privacy, [p,r,i,v,a,c,y]).
word(private, [p,r,i,v,a,t,e]).
word(probably, [p,r,o,b,a,b,l,y]).
word(problem, [p,r,o,b,l,e,m]).
word(procedure, [p,r,o,c,e,d,u,r,e]).
word(proceed, [p,r,o,c,e,e,d]).
word(process, [p,r,o,c,e,s,s]).
word(produce, [p,r,o,d,u,c,e]).
word(producer, [p,r,o,d,u,c,e,r]).
word(product, [p,r,o,d,u,c,t]).
word(production, [p,r,o,d,u,c,t,i,o,n]).
word(profession, [p,r,o,f,e,s,s,i,o,n]).
word(professional, [p,r,o,f,e,s,s,i,o,n,a,l]).
word(professor, [p,r,o,f,e,s,s,o,r]).
word(profile, [p,r,o,f,i,l,e]).
word(profit, [p,r,o,f,i,t]).
word(program, [p,r,o,g,r,a,m]).
word(progress, [p,r,o,g,r,e,s,s]).
word(project, [p,r,o,j,e,c,t]).
word(prominent, [p,r,o,m,i,n,e,n,t]).
word(promise, [p,r,o,m,i,s,e]).
word(promote, [p,r,o,m,o,t,e]).
word(prompt, [p,r,o,m,p,t]).
word(proof, [p,r,o,o,f]).
word(proper, [p,r,o,p,e,r]).
word(properly, [p,r,o,p,e,r,l,y]).
word(property, [p,r,o,p,e,r,t,y]).
word(proportion, [p,r,o,p,o,r,t,i,o,n]).
word(proposal, [p,r,o,p,o,s,a,l]).
word(propose, [p,r,o,p,o,s,e]).
word(proposed, [p,r,o,p,o,s,e,d]).
word(prosecutor, [p,r,o,s,e,c,u,t,o,r]).
word(prospect, [p,r,o,s,p,e,c,t]).
word(protect, [p,r,o,t,e,c,t]).
word(protection, [p,r,o,t,e,c,t,i,o,n]).
word(protein, [p,r,o,t,e,i,n]).
word(protest, [p,r,o,t,e,s,t]).
word(proud, [p,r,o,u,d]).
word(prove, [p,r,o,v,e]).
word(provide, [p,r,o,v,i,d,e]).
word(provider, [p,r,o,v,i,d,e,r]).
word(province, [p,r,o,v,i,n,c,e]).
word(provision, [p,r,o,v,i,s,i,o,n]).
word(psychological, [p,s,y,c,h,o,l,o,g,i,c,a,l]).
word(psychologist, [p,s,y,c,h,o,l,o,g,i,s,t]).
word(psychology, [p,s,y,c,h,o,l,o,g,y]).
word(public, [p,u,b,l,i,c]).
word(publication, [p,u,b,l,i,c,a,t,i,o,n]).
word(publicly, [p,u,b,l,i,c,l,y]).
word(publish, [p,u,b,l,i,s,h]).
word(publisher, [p,u,b,l,i,s,h,e,r]).
word(pull, [p,u,l,l]).
word(punishment, [p,u,n,i,s,h,m,e,n,t]).
word(purchase, [p,u,r,c,h,a,s,e]).
word(pure, [p,u,r,e]).
word(purpose, [p,u,r,p,o,s,e]).
word(pursue, [p,u,r,s,u,e]).
word(push, [p,u,s,h]).
word(put, [p,u,t]).
word(qualify, [q,u,a,l,i,f,y]).
word(quality, [q,u,a,l,i,t,y]).
word(quarter, [q,u,a,r,t,e,r]).
word(quarterback, [q,u,a,r,t,e,r,b,a,c,k]).
word(question, [q,u,e,s,t,i,o,n]).
word(quick, [q,u,i,c,k]).
word(quickly, [q,u,i,c,k,l,y]).
word(quiet, [q,u,i,e,t]).
word(quietly, [q,u,i,e,t,l,y]).
word(quit, [q,u,i,t]).
word(quite, [q,u,i,t,e]).
word(quote, [q,u,o,t,e]).
word(race, [r,a,c,e]).
word(racial, [r,a,c,i,a,l]).
word(radical, [r,a,d,i,c,a,l]).
word(radio, [r,a,d,i,o]).
word(rail, [r,a,i,l]).
word(rain, [r,a,i,n]).
word(raise, [r,a,i,s,e]).
word(range, [r,a,n,g,e]).
word(rank, [r,a,n,k]).
word(rapid, [r,a,p,i,d]).
word(rapidly, [r,a,p,i,d,l,y]).
word(rare, [r,a,r,e]).
word(rarely, [r,a,r,e,l,y]).
word(rate, [r,a,t,e]).
word(rather, [r,a,t,h,e,r]).
word(rating, [r,a,t,i,n,g]).
word(ratio, [r,a,t,i,o]).
word(raw, [r,a,w]).
word(reach, [r,e,a,c,h]).
word(react, [r,e,a,c,t]).
word(reaction, [r,e,a,c,t,i,o,n]).
word(read, [r,e,a,d]).
word(reader, [r,e,a,d,e,r]).
word(reading, [r,e,a,d,i,n,g]).
word(ready, [r,e,a,d,y]).
word(real, [r,e,a,l]).
word(reality, [r,e,a,l,i,t,y]).
word(realize, [r,e,a,l,i,z,e]).
word(really, [r,e,a,l,l,y]).
word(reason, [r,e,a,s,o,n]).
word(reasonable, [r,e,a,s,o,n,a,b,l,e]).
word(recall, [r,e,c,a,l,l]).
word(receive, [r,e,c,e,i,v,e]).
word(recent, [r,e,c,e,n,t]).
word(recently, [r,e,c,e,n,t,l,y]).
word(recipe, [r,e,c,i,p,e]).
word(recognition, [r,e,c,o,g,n,i,t,i,o,n]).
word(recognize, [r,e,c,o,g,n,i,z,e]).
word(recommend, [r,e,c,o,m,m,e,n,d]).
word(recommendation, [r,e,c,o,m,m,e,n,d,a,t,i,o,n]).
word(record, [r,e,c,o,r,d]).
word(recording, [r,e,c,o,r,d,i,n,g]).
word(recover, [r,e,c,o,v,e,r]).
word(recovery, [r,e,c,o,v,e,r,y]).
word(recruit, [r,e,c,r,u,i,t]).
word(red, [r,e,d]).
word(reduce, [r,e,d,u,c,e]).
word(reduction, [r,e,d,u,c,t,i,o,n]).
word(refer, [r,e,f,e,r]).
word(reference, [r,e,f,e,r,e,n,c,e]).
word(reflect, [r,e,f,l,e,c,t]).
word(reflection, [r,e,f,l,e,c,t,i,o,n]).
word(reform, [r,e,f,o,r,m]).
word(refugee, [r,e,f,u,g,e,e]).
word(refuse, [r,e,f,u,s,e]).
word(regard, [r,e,g,a,r,d]).
word(regarding, [r,e,g,a,r,d,i,n,g]).
word(regardless, [r,e,g,a,r,d,l,e,s,s]).
word(regime, [r,e,g,i,m,e]).
word(region, [r,e,g,i,o,n]).
word(regional, [r,e,g,i,o,n,a,l]).
word(register, [r,e,g,i,s,t,e,r]).
word(regular, [r,e,g,u,l,a,r]).
word(regularly, [r,e,g,u,l,a,r,l,y]).
word(regulate, [r,e,g,u,l,a,t,e]).
word(regulation, [r,e,g,u,l,a,t,i,o,n]).
word(reinforce, [r,e,i,n,f,o,r,c,e]).
word(reject, [r,e,j,e,c,t]).
word(relate, [r,e,l,a,t,e]).
word(relation, [r,e,l,a,t,i,o,n]).
word(relationship, [r,e,l,a,t,i,o,n,s,h,i,p]).
word(relative, [r,e,l,a,t,i,v,e]).
word(relatively, [r,e,l,a,t,i,v,e,l,y]).
word(relax, [r,e,l,a,x]).
word(release, [r,e,l,e,a,s,e]).
word(relevant, [r,e,l,e,v,a,n,t]).
word(relief, [r,e,l,i,e,f]).
word(religion, [r,e,l,i,g,i,o,n]).
word(religious, [r,e,l,i,g,i,o,u,s]).
word(rely, [r,e,l,y]).
word(remain, [r,e,m,a,i,n]).
word(remaining, [r,e,m,a,i,n,i,n,g]).
word(remarkable, [r,e,m,a,r,k,a,b,l,e]).
word(remember, [r,e,m,e,m,b,e,r]).
word(remind, [r,e,m,i,n,d]).
word(remote, [r,e,m,o,t,e]).
word(remove, [r,e,m,o,v,e]).
word(repeat, [r,e,p,e,a,t]).
word(repeatedly, [r,e,p,e,a,t,e,d,l,y]).
word(replace, [r,e,p,l,a,c,e]).
word(reply, [r,e,p,l,y]).
word(report, [r,e,p,o,r,t]).
word(reporter, [r,e,p,o,r,t,e,r]).
word(represent, [r,e,p,r,e,s,e,n,t]).
word(representation, [r,e,p,r,e,s,e,n,t,a,t,i,o,n]).
word(representative, [r,e,p,r,e,s,e,n,t,a,t,i,v,e]).
word(republican, [r,e,p,u,b,l,i,c,a,n]).
word(reputation, [r,e,p,u,t,a,t,i,o,n]).
word(request, [r,e,q,u,e,s,t]).
word(require, [r,e,q,u,i,r,e]).
word(requirement, [r,e,q,u,i,r,e,m,e,n,t]).
word(research, [r,e,s,e,a,r,c,h]).
word(researcher, [r,e,s,e,a,r,c,h,e,r]).
word(resemble, [r,e,s,e,m,b,l,e]).
word(reservation, [r,e,s,e,r,v,a,t,i,o,n]).
word(resident, [r,e,s,i,d,e,n,t]).
word(resist, [r,e,s,i,s,t]).
word(resistance, [r,e,s,i,s,t,a,n,c,e]).
word(resolution, [r,e,s,o,l,u,t,i,o,n]).
word(resolve, [r,e,s,o,l,v,e]).
word(resort, [r,e,s,o,r,t]).
word(resource, [r,e,s,o,u,r,c,e]).
word(respect, [r,e,s,p,e,c,t]).
word(respond, [r,e,s,p,o,n,d]).
word(respondent, [r,e,s,p,o,n,d,e,n,t]).
word(response, [r,e,s,p,o,n,s,e]).
word(responsibility, [r,e,s,p,o,n,s,i,b,i,l,i,t,y]).
word(responsible, [r,e,s,p,o,n,s,i,b,l,e]).
word(rest, [r,e,s,t]).
word(restaurant, [r,e,s,t,a,u,r,a,n,t]).
word(restore, [r,e,s,t,o,r,e]).
word(restriction, [r,e,s,t,r,i,c,t,i,o,n]).
word(result, [r,e,s,u,l,t]).
word(retain, [r,e,t,a,i,n]).
word(retire, [r,e,t,i,r,e]).
word(retirement, [r,e,t,i,r,e,m,e,n,t]).
word(return, [r,e,t,u,r,n]).
word(reveal, [r,e,v,e,a,l]).
word(revenue, [r,e,v,e,n,u,e]).
word(review, [r,e,v,i,e,w]).
word(revolution, [r,e,v,o,l,u,t,i,o,n]).
word(rhythm, [r,h,y,t,h,m]).
word(rice, [r,i,c,e]).
word(rich, [r,i,c,h]).
word(rid, [r,i,d]).
word(ride, [r,i,d,e]).
word(rifle, [r,i,f,l,e]).
word(right, [r,i,g,h,t]).
word(ring, [r,i,n,g]).
word(rise, [r,i,s,e]).
word(risk, [r,i,s,k]).
word(river, [r,i,v,e,r]).
word(road, [r,o,a,d]).
word(rock, [r,o,c,k]).
word(role, [r,o,l,e]).
word(roll, [r,o,l,l]).
word(romantic, [r,o,m,a,n,t,i,c]).
word(roof, [r,o,o,f]).
word(room, [r,o,o,m]).
word(root, [r,o,o,t]).
word(rope, [r,o,p,e]).
word(rose, [r,o,s,e]).
word(rough, [r,o,u,g,h]).
word(roughly, [r,o,u,g,h,l,y]).
word(round, [r,o,u,n,d]).
word(route, [r,o,u,t,e]).
word(routine, [r,o,u,t,i,n,e]).
word(row, [r,o,w]).
word(rub, [r,u,b]).
word(rule, [r,u,l,e]).
word(run, [r,u,n]).
word(running, [r,u,n,n,i,n,g]).
word(rural, [r,u,r,a,l]).
word(rush, [r,u,s,h]).
word(russian, [r,u,s,s,i,a,n]).
word(sacred, [s,a,c,r,e,d]).
word(sad, [s,a,d]).
word(safe, [s,a,f,e]).
word(safety, [s,a,f,e,t,y]).
word(sake, [s,a,k,e]).
word(salad, [s,a,l,a,d]).
word(salary, [s,a,l,a,r,y]).
word(sale, [s,a,l,e]).
word(sales, [s,a,l,e,s]).
word(salt, [s,a,l,t]).
word(same, [s,a,m,e]).
word(sample, [s,a,m,p,l,e]).
word(sanction, [s,a,n,c,t,i,o,n]).
word(sand, [s,a,n,d]).
word(satellite, [s,a,t,e,l,l,i,t,e]).
word(satisfaction, [s,a,t,i,s,f,a,c,t,i,o,n]).
word(satisfy, [s,a,t,i,s,f,y]).
word(sauce, [s,a,u,c,e]).
word(save, [s,a,v,e]).
word(saving, [s,a,v,i,n,g]).
word(say, [s,a,y]).
word(scale, [s,c,a,l,e]).
word(scandal, [s,c,a,n,d,a,l]).
word(scared, [s,c,a,r,e,d]).
word(scenario, [s,c,e,n,a,r,i,o]).
word(scene, [s,c,e,n,e]).
word(schedule, [s,c,h,e,d,u,l,e]).
word(scheme, [s,c,h,e,m,e]).
word(scholar, [s,c,h,o,l,a,r]).
word(scholarship, [s,c,h,o,l,a,r,s,h,i,p]).
word(school, [s,c,h,o,o,l]).
word(science, [s,c,i,e,n,c,e]).
word(scientific, [s,c,i,e,n,t,i,f,i,c]).
word(scientist, [s,c,i,e,n,t,i,s,t]).
word(scope, [s,c,o,p,e]).
word(score, [s,c,o,r,e]).
word(scream, [s,c,r,e,a,m]).
word(screen, [s,c,r,e,e,n]).
word(script, [s,c,r,i,p,t]).
word(sea, [s,e,a]).
word(search, [s,e,a,r,c,h]).
word(season, [s,e,a,s,o,n]).
word(seat, [s,e,a,t]).
word(second, [s,e,c,o,n,d]).
word(secret, [s,e,c,r,e,t]).
word(secretary, [s,e,c,r,e,t,a,r,y]).
word(section, [s,e,c,t,i,o,n]).
word(sector, [s,e,c,t,o,r]).
word(secure, [s,e,c,u,r,e]).
word(security, [s,e,c,u,r,i,t,y]).
word(see, [s,e,e]).
word(seed, [s,e,e,d]).
word(seek, [s,e,e,k]).
word(seem, [s,e,e,m]).
word(segment, [s,e,g,m,e,n,t]).
word(seize, [s,e,i,z,e]).
word(select, [s,e,l,e,c,t]).
word(selection, [s,e,l,e,c,t,i,o,n]).
word(self, [s,e,l,f]).
word(sell, [s,e,l,l]).
word(senate, [s,e,n,a,t,e]).
word(senator, [s,e,n,a,t,o,r]).
word(send, [s,e,n,d]).
word(senior, [s,e,n,i,o,r]).
word(sense, [s,e,n,s,e]).
word(sensitive, [s,e,n,s,i,t,i,v,e]).
word(sentence, [s,e,n,t,e,n,c,e]).
word(separate, [s,e,p,a,r,a,t,e]).
word(sequence, [s,e,q,u,e,n,c,e]).
word(series, [s,e,r,i,e,s]).
word(serious, [s,e,r,i,o,u,s]).
word(seriously, [s,e,r,i,o,u,s,l,y]).
word(serve, [s,e,r,v,e]).
word(service, [s,e,r,v,i,c,e]).
word(session, [s,e,s,s,i,o,n]).
word(set, [s,e,t]).
word(setting, [s,e,t,t,i,n,g]).
word(settle, [s,e,t,t,l,e]).
word(settlement, [s,e,t,t,l,e,m,e,n,t]).
word(seven, [s,e,v,e,n]).
word(several, [s,e,v,e,r,a,l]).
word(severe, [s,e,v,e,r,e]).
word(sex, [s,e,x]).
word(sexual, [s,e,x,u,a,l]).
word(shade, [s,h,a,d,e]).
word(shadow, [s,h,a,d,o,w]).
word(shake, [s,h,a,k,e]).
word(shall, [s,h,a,l,l]).
word(shape, [s,h,a,p,e]).
word(share, [s,h,a,r,e]).
word(sharp, [s,h,a,r,p]).
word(she, [s,h,e]).
word(sheet, [s,h,e,e,t]).
word(shelf, [s,h,e,l,f]).
word(shell, [s,h,e,l,l]).
word(shelter, [s,h,e,l,t,e,r]).
word(shift, [s,h,i,f,t]).
word(shine, [s,h,i,n,e]).
word(ship, [s,h,i,p]).
word(shirt, [s,h,i,r,t]).
word(shit, [s,h,i,t]).
word(shock, [s,h,o,c,k]).
word(shoe, [s,h,o,e]).
word(shoot, [s,h,o,o,t]).
word(shooting, [s,h,o,o,t,i,n,g]).
word(shop, [s,h,o,p]).
word(shopping, [s,h,o,p,p,i,n,g]).
word(shore, [s,h,o,r,e]).
word(short, [s,h,o,r,t]).
word(shortly, [s,h,o,r,t,l,y]).
word(shot, [s,h,o,t]).
word(should, [s,h,o,u,l,d]).
word(shoulder, [s,h,o,u,l,d,e,r]).
word(shout, [s,h,o,u,t]).
word(show, [s,h,o,w]).
word(shower, [s,h,o,w,e,r]).
word(shrug, [s,h,r,u,g]).
word(shut, [s,h,u,t]).
word(sick, [s,i,c,k]).
word(side, [s,i,d,e]).
word(sigh, [s,i,g,h]).
word(sight, [s,i,g,h,t]).
word(sign, [s,i,g,n]).
word(signal, [s,i,g,n,a,l]).
word(significance, [s,i,g,n,i,f,i,c,a,n,c,e]).
word(significant, [s,i,g,n,i,f,i,c,a,n,t]).
word(significantly, [s,i,g,n,i,f,i,c,a,n,t,l,y]).
word(silence, [s,i,l,e,n,c,e]).
word(silent, [s,i,l,e,n,t]).
word(silver, [s,i,l,v,e,r]).
word(similar, [s,i,m,i,l,a,r]).
word(similarly, [s,i,m,i,l,a,r,l,y]).
word(simple, [s,i,m,p,l,e]).
word(simply, [s,i,m,p,l,y]).
word(sin, [s,i,n]).
word(since, [s,i,n,c,e]).
word(sing, [s,i,n,g]).
word(singer, [s,i,n,g,e,r]).
word(single, [s,i,n,g,l,e]).
word(sink, [s,i,n,k]).
word(sir, [s,i,r]).
word(sister, [s,i,s,t,e,r]).
word(sit, [s,i,t]).
word(site, [s,i,t,e]).
word(situation, [s,i,t,u,a,t,i,o,n]).
word(six, [s,i,x]).
word(size, [s,i,z,e]).
word(ski, [s,k,i]).
word(skill, [s,k,i,l,l]).
word(skin, [s,k,i,n]).
word(sky, [s,k,y]).
word(slave, [s,l,a,v,e]).
word(sleep, [s,l,e,e,p]).
word(slice, [s,l,i,c,e]).
word(slide, [s,l,i,d,e]).
word(slight, [s,l,i,g,h,t]).
word(slightly, [s,l,i,g,h,t,l,y]).
word(slip, [s,l,i,p]).
word(slow, [s,l,o,w]).
word(slowly, [s,l,o,w,l,y]).
word(small, [s,m,a,l,l]).
word(smart, [s,m,a,r,t]).
word(smell, [s,m,e,l,l]).
word(smile, [s,m,i,l,e]).
word(smoke, [s,m,o,k,e]).
word(smooth, [s,m,o,o,t,h]).
word(snap, [s,n,a,p]).
word(snow, [s,n,o,w]).
word(so, [s,o]).
word(soccer, [s,o,c,c,e,r]).
word(social, [s,o,c,i,a,l]).
word(society, [s,o,c,i,e,t,y]).
word(soft, [s,o,f,t]).
word(software, [s,o,f,t,w,a,r,e]).
word(soil, [s,o,i,l]).
word(solar, [s,o,l,a,r]).
word(soldier, [s,o,l,d,i,e,r]).
word(solid, [s,o,l,i,d]).
word(solution, [s,o,l,u,t,i,o,n]).
word(solve, [s,o,l,v,e]).
word(some, [s,o,m,e]).
word(somebody, [s,o,m,e,b,o,d,y]).
word(somehow, [s,o,m,e,h,o,w]).
word(someone, [s,o,m,e,o,n,e]).
word(something, [s,o,m,e,t,h,i,n,g]).
word(sometimes, [s,o,m,e,t,i,m,e,s]).
word(somewhat, [s,o,m,e,w,h,a,t]).
word(somewhere, [s,o,m,e,w,h,e,r,e]).
word(son, [s,o,n]).
word(song, [s,o,n,g]).
word(soon, [s,o,o,n]).
word(sophisticated, [s,o,p,h,i,s,t,i,c,a,t,e,d]).
word(sorry, [s,o,r,r,y]).
word(sort, [s,o,r,t]).
word(soul, [s,o,u,l]).
word(sound, [s,o,u,n,d]).
word(soup, [s,o,u,p]).
word(source, [s,o,u,r,c,e]).
word(south, [s,o,u,t,h]).
word(southern, [s,o,u,t,h,e,r,n]).
word(soviet, [s,o,v,i,e,t]).
word(space, [s,p,a,c,e]).
word(spanish, [s,p,a,n,i,s,h]).
word(speak, [s,p,e,a,k]).
word(speaker, [s,p,e,a,k,e,r]).
word(special, [s,p,e,c,i,a,l]).
word(specialist, [s,p,e,c,i,a,l,i,s,t]).
word(species, [s,p,e,c,i,e,s]).
word(specific, [s,p,e,c,i,f,i,c]).
word(specifically, [s,p,e,c,i,f,i,c,a,l,l,y]).
word(speech, [s,p,e,e,c,h]).
word(speed, [s,p,e,e,d]).
word(spend, [s,p,e,n,d]).
word(spending, [s,p,e,n,d,i,n,g]).
word(spin, [s,p,i,n]).
word(spirit, [s,p,i,r,i,t]).
word(spiritual, [s,p,i,r,i,t,u,a,l]).
word(split, [s,p,l,i,t]).
word(spokesman, [s,p,o,k,e,s,m,a,n]).
word(sport, [s,p,o,r,t]).
word(spot, [s,p,o,t]).
word(spread, [s,p,r,e,a,d]).
word(spring, [s,p,r,i,n,g]).
word(square, [s,q,u,a,r,e]).
word(squeeze, [s,q,u,e,e,z,e]).
word(stability, [s,t,a,b,i,l,i,t,y]).
word(stable, [s,t,a,b,l,e]).
word(staff, [s,t,a,f,f]).
word(stage, [s,t,a,g,e]).
word(stair, [s,t,a,i,r]).
word(stake, [s,t,a,k,e]).
word(stand, [s,t,a,n,d]).
word(standard, [s,t,a,n,d,a,r,d]).
word(standing, [s,t,a,n,d,i,n,g]).
word(star, [s,t,a,r]).
word(stare, [s,t,a,r,e]).
word(start, [s,t,a,r,t]).
word(state, [s,t,a,t,e]).
word(statement, [s,t,a,t,e,m,e,n,t]).
word(station, [s,t,a,t,i,o,n]).
word(statistics, [s,t,a,t,i,s,t,i,c,s]).
word(status, [s,t,a,t,u,s]).
word(stay, [s,t,a,y]).
word(steady, [s,t,e,a,d,y]).
word(steal, [s,t,e,a,l]).
word(steel, [s,t,e,e,l]).
word(step, [s,t,e,p]).
word(stick, [s,t,i,c,k]).
word(still, [s,t,i,l,l]).
word(stir, [s,t,i,r]).
word(stock, [s,t,o,c,k]).
word(stomach, [s,t,o,m,a,c,h]).
word(stone, [s,t,o,n,e]).
word(stop, [s,t,o,p]).
word(storage, [s,t,o,r,a,g,e]).
word(store, [s,t,o,r,e]).
word(storm, [s,t,o,r,m]).
word(story, [s,t,o,r,y]).
word(straight, [s,t,r,a,i,g,h,t]).
word(strange, [s,t,r,a,n,g,e]).
word(stranger, [s,t,r,a,n,g,e,r]).
word(strategic, [s,t,r,a,t,e,g,i,c]).
word(strategy, [s,t,r,a,t,e,g,y]).
word(stream, [s,t,r,e,a,m]).
word(street, [s,t,r,e,e,t]).
word(strength, [s,t,r,e,n,g,t,h]).
word(strengthen, [s,t,r,e,n,g,t,h,e,n]).
word(stress, [s,t,r,e,s,s]).
word(stretch, [s,t,r,e,t,c,h]).
word(strike, [s,t,r,i,k,e]).
word(string, [s,t,r,i,n,g]).
word(strip, [s,t,r,i,p]).
word(stroke, [s,t,r,o,k,e]).
word(strong, [s,t,r,o,n,g]).
word(strongly, [s,t,r,o,n,g,l,y]).
word(structure, [s,t,r,u,c,t,u,r,e]).
word(struggle, [s,t,r,u,g,g,l,e]).
word(student, [s,t,u,d,e,n,t]).
word(studio, [s,t,u,d,i,o]).
word(study, [s,t,u,d,y]).
word(stuff, [s,t,u,f,f]).
word(stupid, [s,t,u,p,i,d]).
word(style, [s,t,y,l,e]).
word(subject, [s,u,b,j,e,c,t]).
word(submit, [s,u,b,m,i,t]).
word(subsequent, [s,u,b,s,e,q,u,e,n,t]).
word(substance, [s,u,b,s,t,a,n,c,e]).
word(substantial, [s,u,b,s,t,a,n,t,i,a,l]).
word(succeed, [s,u,c,c,e,e,d]).
word(success, [s,u,c,c,e,s,s]).
word(successful, [s,u,c,c,e,s,s,f,u,l]).
word(successfully, [s,u,c,c,e,s,s,f,u,l,l,y]).
word(such, [s,u,c,h]).
word(sudden, [s,u,d,d,e,n]).
word(suddenly, [s,u,d,d,e,n,l,y]).
word(sue, [s,u,e]).
word(suffer, [s,u,f,f,e,r]).
word(sufficient, [s,u,f,f,i,c,i,e,n,t]).
word(sugar, [s,u,g,a,r]).
word(suggest, [s,u,g,g,e,s,t]).
word(suggestion, [s,u,g,g,e,s,t,i,o,n]).
word(suicide, [s,u,i,c,i,d,e]).
word(suit, [s,u,i,t]).
word(summer, [s,u,m,m,e,r]).
word(summit, [s,u,m,m,i,t]).
word(sun, [s,u,n]).
word(super, [s,u,p,e,r]).
word(supply, [s,u,p,p,l,y]).
word(support, [s,u,p,p,o,r,t]).
word(supporter, [s,u,p,p,o,r,t,e,r]).
word(suppose, [s,u,p,p,o,s,e]).
word(supposed, [s,u,p,p,o,s,e,d]).
word(supreme, [s,u,p,r,e,m,e]).
word(sure, [s,u,r,e]).
word(surely, [s,u,r,e,l,y]).
word(surface, [s,u,r,f,a,c,e]).
word(surgery, [s,u,r,g,e,r,y]).
word(surprise, [s,u,r,p,r,i,s,e]).
word(surprised, [s,u,r,p,r,i,s,e,d]).
word(surprising, [s,u,r,p,r,i,s,i,n,g]).
word(surprisingly, [s,u,r,p,r,i,s,i,n,g,l,y]).
word(surround, [s,u,r,r,o,u,n,d]).
word(survey, [s,u,r,v,e,y]).
word(survival, [s,u,r,v,i,v,a,l]).
word(survive, [s,u,r,v,i,v,e]).
word(survivor, [s,u,r,v,i,v,o,r]).
word(suspect, [s,u,s,p,e,c,t]).
word(sustain, [s,u,s,t,a,i,n]).
word(swear, [s,w,e,a,r]).
word(sweep, [s,w,e,e,p]).
word(sweet, [s,w,e,e,t]).
word(swim, [s,w,i,m]).
word(swing, [s,w,i,n,g]).
word(switch, [s,w,i,t,c,h]).
word(symbol, [s,y,m,b,o,l]).
word(symptom, [s,y,m,p,t,o,m]).
word(system, [s,y,s,t,e,m]).
word(table, [t,a,b,l,e]).
word(tablespoon, [t,a,b,l,e,s,p,o,o,n]).
word(tactic, [t,a,c,t,i,c]).
word(tail, [t,a,i,l]).
word(take, [t,a,k,e]).
word(tale, [t,a,l,e]).
word(talent, [t,a,l,e,n,t]).
word(talk, [t,a,l,k]).
word(tall, [t,a,l,l]).
word(tank, [t,a,n,k]).
word(tap, [t,a,p]).
word(tape, [t,a,p,e]).
word(target, [t,a,r,g,e,t]).
word(task, [t,a,s,k]).
word(taste, [t,a,s,t,e]).
word(tax, [t,a,x]).
word(taxpayer, [t,a,x,p,a,y,e,r]).
word(tea, [t,e,a]).
word(teach, [t,e,a,c,h]).
word(teacher, [t,e,a,c,h,e,r]).
word(teaching, [t,e,a,c,h,i,n,g]).
word(team, [t,e,a,m]).
word(tear, [t,e,a,r]).
word(teaspoon, [t,e,a,s,p,o,o,n]).
word(technical, [t,e,c,h,n,i,c,a,l]).
word(technique, [t,e,c,h,n,i,q,u,e]).
word(technology, [t,e,c,h,n,o,l,o,g,y]).
word(teen, [t,e,e,n]).
word(teenager, [t,e,e,n,a,g,e,r]).
word(telephone, [t,e,l,e,p,h,o,n,e]).
word(telescope, [t,e,l,e,s,c,o,p,e]).
word(television, [t,e,l,e,v,i,s,i,o,n]).
word(tell, [t,e,l,l]).
word(temperature, [t,e,m,p,e,r,a,t,u,r,e]).
word(temporary, [t,e,m,p,o,r,a,r,y]).
word(ten, [t,e,n]).
word(tend, [t,e,n,d]).
word(tendency, [t,e,n,d,e,n,c,y]).
word(tennis, [t,e,n,n,i,s]).
word(tension, [t,e,n,s,i,o,n]).
word(tent, [t,e,n,t]).
word(term, [t,e,r,m]).
word(terms, [t,e,r,m,s]).
word(terrible, [t,e,r,r,i,b,l,e]).
word(territory, [t,e,r,r,i,t,o,r,y]).
word(terror, [t,e,r,r,o,r]).
word(terrorism, [t,e,r,r,o,r,i,s,m]).
word(terrorist, [t,e,r,r,o,r,i,s,t]).
word(test, [t,e,s,t]).
word(testify, [t,e,s,t,i,f,y]).
word(testimony, [t,e,s,t,i,m,o,n,y]).
word(testing, [t,e,s,t,i,n,g]).
word(text, [t,e,x,t]).
word(than, [t,h,a,n]).
word(thank, [t,h,a,n,k]).
word(thanks, [t,h,a,n,k,s]).
word(that, [t,h,a,t]).
word(the, [t,h,e]).
word(theater, [t,h,e,a,t,e,r]).
word(their, [t,h,e,i,r]).
word(them, [t,h,e,m]).
word(theme, [t,h,e,m,e]).
word(themselves, [t,h,e,m,s,e,l,v,e,s]).
word(then, [t,h,e,n]).
word(theory, [t,h,e,o,r,y]).
word(therapy, [t,h,e,r,a,p,y]).
word(there, [t,h,e,r,e]).
word(therefore, [t,h,e,r,e,f,o,r,e]).
word(these, [t,h,e,s,e]).
word(they, [t,h,e,y]).
word(thick, [t,h,i,c,k]).
word(thin, [t,h,i,n]).
word(thing, [t,h,i,n,g]).
word(think, [t,h,i,n,k]).
word(thinking, [t,h,i,n,k,i,n,g]).
word(third, [t,h,i,r,d]).
word(thirty, [t,h,i,r,t,y]).
word(this, [t,h,i,s]).
word(those, [t,h,o,s,e]).
word(though, [t,h,o,u,g,h]).
word(thought, [t,h,o,u,g,h,t]).
word(thousand, [t,h,o,u,s,a,n,d]).
word(threat, [t,h,r,e,a,t]).
word(threaten, [t,h,r,e,a,t,e,n]).
word(three, [t,h,r,e,e]).
word(throat, [t,h,r,o,a,t]).
word(through, [t,h,r,o,u,g,h]).
word(throughout, [t,h,r,o,u,g,h,o,u,t]).
word(throw, [t,h,r,o,w]).
word(thus, [t,h,u,s]).
word(ticket, [t,i,c,k,e,t]).
word(tie, [t,i,e]).
word(tight, [t,i,g,h,t]).
word(time, [t,i,m,e]).
word(tiny, [t,i,n,y]).
word(tip, [t,i,p]).
word(tire, [t,i,r,e]).
word(tired, [t,i,r,e,d]).
word(tissue, [t,i,s,s,u,e]).
word(title, [t,i,t,l,e]).
word(to, [t,o]).
word(tobacco, [t,o,b,a,c,c,o]).
word(today, [t,o,d,a,y]).
word(toe, [t,o,e]).
word(together, [t,o,g,e,t,h,e,r]).
word(tomato, [t,o,m,a,t,o]).
word(tomorrow, [t,o,m,o,r,r,o,w]).
word(tone, [t,o,n,e]).
word(tongue, [t,o,n,g,u,e]).
word(tonight, [t,o,n,i,g,h,t]).
word(too, [t,o,o]).
word(tool, [t,o,o,l]).
word(tooth, [t,o,o,t,h]).
word(top, [t,o,p]).
word(topic, [t,o,p,i,c]).
word(toss, [t,o,s,s]).
word(total, [t,o,t,a,l]).
word(totally, [t,o,t,a,l,l,y]).
word(touch, [t,o,u,c,h]).
word(tough, [t,o,u,g,h]).
word(tour, [t,o,u,r]).
word(tourist, [t,o,u,r,i,s,t]).
word(tournament, [t,o,u,r,n,a,m,e,n,t]).
word(toward, [t,o,w,a,r,d]).
word(towards, [t,o,w,a,r,d,s]).
word(tower, [t,o,w,e,r]).
word(town, [t,o,w,n]).
word(toy, [t,o,y]).
word(trace, [t,r,a,c,e]).
word(track, [t,r,a,c,k]).
word(trade, [t,r,a,d,e]).
word(tradition, [t,r,a,d,i,t,i,o,n]).
word(traditional, [t,r,a,d,i,t,i,o,n,a,l]).
word(traffic, [t,r,a,f,f,i,c]).
word(tragedy, [t,r,a,g,e,d,y]).
word(trail, [t,r,a,i,l]).
word(train, [t,r,a,i,n]).
word(training, [t,r,a,i,n,i,n,g]).
word(transfer, [t,r,a,n,s,f,e,r]).
word(transform, [t,r,a,n,s,f,o,r,m]).
word(transformation, [t,r,a,n,s,f,o,r,m,a,t,i,o,n]).
word(transition, [t,r,a,n,s,i,t,i,o,n]).
word(translate, [t,r,a,n,s,l,a,t,e]).
word(transportation, [t,r,a,n,s,p,o,r,t,a,t,i,o,n]).
word(travel, [t,r,a,v,e,l]).
word(treat, [t,r,e,a,t]).
word(treatment, [t,r,e,a,t,m,e,n,t]).
word(treaty, [t,r,e,a,t,y]).
word(tree, [t,r,e,e]).
word(tremendous, [t,r,e,m,e,n,d,o,u,s]).
word(trend, [t,r,e,n,d]).
word(trial, [t,r,i,a,l]).
word(tribe, [t,r,i,b,e]).
word(trick, [t,r,i,c,k]).
word(trip, [t,r,i,p]).
word(troop, [t,r,o,o,p]).
word(trouble, [t,r,o,u,b,l,e]).
word(truck, [t,r,u,c,k]).
word(true, [t,r,u,e]).
word(truly, [t,r,u,l,y]).
word(trust, [t,r,u,s,t]).
word(truth, [t,r,u,t,h]).
word(try, [t,r,y]).
word(tube, [t,u,b,e]).
word(tunnel, [t,u,n,n,e,l]).
word(turn, [t,u,r,n]).
word(tv, [t,v]).
word(twelve, [t,w,e,l,v,e]).
word(twenty, [t,w,e,n,t,y]).
word(twice, [t,w,i,c,e]).
word(twin, [t,w,i,n]).
word(two, [t,w,o]).
word(type, [t,y,p,e]).
word(typical, [t,y,p,i,c,a,l]).
word(typically, [t,y,p,i,c,a,l,l,y]).
word(ugly, [u,g,l,y]).
word(ultimate, [u,l,t,i,m,a,t,e]).
word(ultimately, [u,l,t,i,m,a,t,e,l,y]).
word(unable, [u,n,a,b,l,e]).
word(uncle, [u,n,c,l,e]).
word(under, [u,n,d,e,r]).
word(undergo, [u,n,d,e,r,g,o]).
word(understand, [u,n,d,e,r,s,t,a,n,d]).
word(understanding, [u,n,d,e,r,s,t,a,n,d,i,n,g]).
word(unfortunately, [u,n,f,o,r,t,u,n,a,t,e,l,y]).
word(uniform, [u,n,i,f,o,r,m]).
word(union, [u,n,i,o,n]).
word(unique, [u,n,i,q,u,e]).
word(unit, [u,n,i,t]).
word(united, [u,n,i,t,e,d]).
word(universal, [u,n,i,v,e,r,s,a,l]).
word(universe, [u,n,i,v,e,r,s,e]).
word(university, [u,n,i,v,e,r,s,i,t,y]).
word(unknown, [u,n,k,n,o,w,n]).
word(unless, [u,n,l,e,s,s]).
word(unlike, [u,n,l,i,k,e]).
word(unlikely, [u,n,l,i,k,e,l,y]).
word(until, [u,n,t,i,l]).
word(unusual, [u,n,u,s,u,a,l]).
word(up, [u,p]).
word(upon, [u,p,o,n]).
word(upper, [u,p,p,e,r]).
word(urban, [u,r,b,a,n]).
word(urge, [u,r,g,e]).
word(us, [u,s]).
word(use, [u,s,e]).
word(used, [u,s,e,d]).
word(useful, [u,s,e,f,u,l]).
word(user, [u,s,e,r]).
word(usual, [u,s,u,a,l]).
word(usually, [u,s,u,a,l,l,y]).
word(utility, [u,t,i,l,i,t,y]).
word(vacation, [v,a,c,a,t,i,o,n]).
word(valley, [v,a,l,l,e,y]).
word(valuable, [v,a,l,u,a,b,l,e]).
word(value, [v,a,l,u,e]).
word(variable, [v,a,r,i,a,b,l,e]).
word(variation, [v,a,r,i,a,t,i,o,n]).
word(variety, [v,a,r,i,e,t,y]).
word(various, [v,a,r,i,o,u,s]).
word(vary, [v,a,r,y]).
word(vast, [v,a,s,t]).
word(vegetable, [v,e,g,e,t,a,b,l,e]).
word(vehicle, [v,e,h,i,c,l,e]).
word(venture, [v,e,n,t,u,r,e]).
word(version, [v,e,r,s,i,o,n]).
word(versus, [v,e,r,s,u,s]).
word(very, [v,e,r,y]).
word(vessel, [v,e,s,s,e,l]).
word(veteran, [v,e,t,e,r,a,n]).
word(via, [v,i,a]).
word(victim, [v,i,c,t,i,m]).
word(victory, [v,i,c,t,o,r,y]).
word(video, [v,i,d,e,o]).
word(view, [v,i,e,w]).
word(viewer, [v,i,e,w,e,r]).
word(village, [v,i,l,l,a,g,e]).
word(violate, [v,i,o,l,a,t,e]).
word(violation, [v,i,o,l,a,t,i,o,n]).
word(violence, [v,i,o,l,e,n,c,e]).
word(violent, [v,i,o,l,e,n,t]).
word(virtually, [v,i,r,t,u,a,l,l,y]).
word(virtue, [v,i,r,t,u,e]).
word(virus, [v,i,r,u,s]).
word(visible, [v,i,s,i,b,l,e]).
word(vision, [v,i,s,i,o,n]).
word(visit, [v,i,s,i,t]).
word(visitor, [v,i,s,i,t,o,r]).
word(visual, [v,i,s,u,a,l]).
word(vital, [v,i,t,a,l]).
word(voice, [v,o,i,c,e]).
word(volume, [v,o,l,u,m,e]).
word(volunteer, [v,o,l,u,n,t,e,e,r]).
word(vote, [v,o,t,e]).
word(voter, [v,o,t,e,r]).
word(vs, [v,s]).
word(vulnerable, [v,u,l,n,e,r,a,b,l,e]).
word(wage, [w,a,g,e]).
word(wait, [w,a,i,t]).
word(wake, [w,a,k,e]).
word(walk, [w,a,l,k]).
word(wall, [w,a,l,l]).
word(wander, [w,a,n,d,e,r]).
word(want, [w,a,n,t]).
word(war, [w,a,r]).
word(warm, [w,a,r,m]).
word(warn, [w,a,r,n]).
word(warning, [w,a,r,n,i,n,g]).
word(wash, [w,a,s,h]).
word(waste, [w,a,s,t,e]).
word(watch, [w,a,t,c,h]).
word(water, [w,a,t,e,r]).
word(wave, [w,a,v,e]).
word(way, [w,a,y]).
word(we, [w,e]).
word(weak, [w,e,a,k]).
word(wealth, [w,e,a,l,t,h]).
word(wealthy, [w,e,a,l,t,h,y]).
word(weapon, [w,e,a,p,o,n]).
word(wear, [w,e,a,r]).
word(weather, [w,e,a,t,h,e,r]).
word(wedding, [w,e,d,d,i,n,g]).
word(week, [w,e,e,k]).
word(weekend, [w,e,e,k,e,n,d]).
word(weekly, [w,e,e,k,l,y]).
word(weigh, [w,e,i,g,h]).
word(weight, [w,e,i,g,h,t]).
word(welcome, [w,e,l,c,o,m,e]).
word(welfare, [w,e,l,f,a,r,e]).
word(well, [w,e,l,l]).
word(west, [w,e,s,t]).
word(western, [w,e,s,t,e,r,n]).
word(wet, [w,e,t]).
word(what, [w,h,a,t]).
word(whatever, [w,h,a,t,e,v,e,r]).
word(wheel, [w,h,e,e,l]).
word(when, [w,h,e,n]).
word(whenever, [w,h,e,n,e,v,e,r]).
word(where, [w,h,e,r,e]).
word(whereas, [w,h,e,r,e,a,s]).
word(whether, [w,h,e,t,h,e,r]).
word(which, [w,h,i,c,h]).
word(while, [w,h,i,l,e]).
word(whisper, [w,h,i,s,p,e,r]).
word(white, [w,h,i,t,e]).
word(who, [w,h,o]).
word(whole, [w,h,o,l,e]).
word(whom, [w,h,o,m]).
word(whose, [w,h,o,s,e]).
word(why, [w,h,y]).
word(wide, [w,i,d,e]).
word(widely, [w,i,d,e,l,y]).
word(widespread, [w,i,d,e,s,p,r,e,a,d]).
word(wife, [w,i,f,e]).
word(wild, [w,i,l,d]).
word(will, [w,i,l,l]).
word(willing, [w,i,l,l,i,n,g]).
word(win, [w,i,n]).
word(wind, [w,i,n,d]).
word(window, [w,i,n,d,o,w]).
word(wine, [w,i,n,e]).
word(wing, [w,i,n,g]).
word(winner, [w,i,n,n,e,r]).
word(winter, [w,i,n,t,e,r]).
word(wipe, [w,i,p,e]).
word(wire, [w,i,r,e]).
word(wisdom, [w,i,s,d,o,m]).
word(wise, [w,i,s,e]).
word(wish, [w,i,s,h]).
word(with, [w,i,t,h]).
word(withdraw, [w,i,t,h,d,r,a,w]).
word(within, [w,i,t,h,i,n]).
word(without, [w,i,t,h,o,u,t]).
word(witness, [w,i,t,n,e,s,s]).
word(woman, [w,o,m,a,n]).
word(wonder, [w,o,n,d,e,r]).
word(wonderful, [w,o,n,d,e,r,f,u,l]).
word(wood, [w,o,o,d]).
word(wooden, [w,o,o,d,e,n]).
word(word, [w,o,r,d]).
word(work, [w,o,r,k]).
word(worker, [w,o,r,k,e,r]).
word(working, [w,o,r,k,i,n,g]).
word(works, [w,o,r,k,s]).
word(workshop, [w,o,r,k,s,h,o,p]).
word(world, [w,o,r,l,d]).
word(worried, [w,o,r,r,i,e,d]).
word(worry, [w,o,r,r,y]).
word(worth, [w,o,r,t,h]).
word(would, [w,o,u,l,d]).
word(wound, [w,o,u,n,d]).
word(wrap, [w,r,a,p]).
word(write, [w,r,i,t,e]).
word(writer, [w,r,i,t,e,r]).
word(writing, [w,r,i,t,i,n,g]).
word(wrong, [w,r,o,n,g]).
word(yard, [y,a,r,d]).
word(yeah, [y,e,a,h]).
word(year, [y,e,a,r]).
word(yell, [y,e,l,l]).
word(yellow, [y,e,l,l,o,w]).
word(yes, [y,e,s]).
word(yesterday, [y,e,s,t,e,r,d,a,y]).
word(yet, [y,e,t]).
word(yield, [y,i,e,l,d]).
word(you, [y,o,u]).
word(young, [y,o,u,n,g]).
word(your, [y,o,u,r]).
word(yours, [y,o,u,r,s]).
word(yourself, [y,o,u,r,s,e,l,f]).
word(youth, [y,o,u,t,h]).
word(zone, [z,o,n,e]).
